export interface ExpiryItem {
  name: string;
  category: string;
  fridgeDays: number | null;
  freezerDays: number | null;
  perishable: boolean;
  keywords: string[];
}

export const EXPIRY_KNOWLEDGE: ExpiryItem[] = [
  // Fruits
  { name: "apple", category: "fruit", fridgeDays: 42, freezerDays: 240, perishable: true, keywords: ["apple", "apples", "gala", "fuji", "granny smith", "honeycrisp"] },
  { name: "avocado", category: "fruit", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["avocado", "avos"] },
  { name: "banana", category: "fruit", fridgeDays: 5, freezerDays: 90, perishable: true, keywords: ["banana", "bananas"] },
  { name: "blueberry", category: "fruit", fridgeDays: 10, freezerDays: 300, perishable: true, keywords: ["blueberry", "blueberries"] },
  { name: "raspberry", category: "fruit", fridgeDays: 3, freezerDays: 180, perishable: true, keywords: ["raspberry", "raspberries"] },
  { name: "strawberry", category: "fruit", fridgeDays: 5, freezerDays: 180, perishable: true, keywords: ["strawberry", "strawberries"] },
  { name: "blackberry", category: "fruit", fridgeDays: 4, freezerDays: 240, perishable: true, keywords: ["blackberry", "blackberries"] },
  { name: "grape", category: "fruit", fridgeDays: 14, freezerDays: 300, perishable: true, keywords: ["grape", "grapes"] },
  { name: "watermelon", category: "fruit", fridgeDays: 14, freezerDays: null, perishable: true, keywords: ["watermelon"] },
  { name: "cantaloupe", category: "fruit", fridgeDays: 7, freezerDays: 300, perishable: true, keywords: ["cantaloupe", "rockmelon"] },
  { name: "honeydew", category: "fruit", fridgeDays: 10, freezerDays: 300, perishable: true, keywords: ["honeydew", "honeydew melon"] },
  { name: "pineapple", category: "fruit", fridgeDays: 5, freezerDays: 180, perishable: true, keywords: ["pineapple"] },
  { name: "mango", category: "fruit", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["mango", "mangoes"] },
  { name: "peach", category: "fruit", fridgeDays: 5, freezerDays: 240, perishable: true, keywords: ["peach", "peaches"] },
  { name: "nectarine", category: "fruit", fridgeDays: 5, freezerDays: 240, perishable: true, keywords: ["nectarine", "nectarines"] },
  { name: "plum", category: "fruit", fridgeDays: 5, freezerDays: 240, perishable: true, keywords: ["plum", "plums"] },
  { name: "cherry", category: "fruit", fridgeDays: 7, freezerDays: 300, perishable: true, keywords: ["cherry", "cherries"] },
  { name: "lemon", category: "fruit", fridgeDays: 28, freezerDays: 90, perishable: true, keywords: ["lemon", "lemons"] },
  { name: "lime", category: "fruit", fridgeDays: 28, freezerDays: 90, perishable: true, keywords: ["lime", "limes"] },
  { name: "grapefruit", category: "fruit", fridgeDays: 21, freezerDays: 30, perishable: true, keywords: ["grapefruit"] },
  { name: "kiwi", category: "fruit", fridgeDays: 14, freezerDays: 240, perishable: true, keywords: ["kiwi", "kiwifruit"] },
  { name: "pear", category: "fruit", fridgeDays: 7, freezerDays: 240, perishable: true, keywords: ["pear", "pears"] },
  { name: "fig", category: "fruit", fridgeDays: 3, freezerDays: 180, perishable: true, keywords: ["fig", "figs"] },
  { name: "pomegranate", category: "fruit", fridgeDays: 30, freezerDays: 365, perishable: true, keywords: ["pomegranate"] },
  { name: "coconut", category: "fruit", fridgeDays: 7, freezerDays: 240, perishable: true, keywords: ["coconut"] },
  { name: "orange", category: "fruit", fridgeDays: 21, freezerDays: 90, perishable: true, keywords: ["orange", "oranges"] },
  { name: "apricot", category: "fruit", fridgeDays: 4, freezerDays: 180, perishable: true, keywords: ["apricot", "apricots"] },
  { name: "cranberry", category: "fruit", fridgeDays: 30, freezerDays: 365, perishable: true, keywords: ["cranberry", "cranberries"] },
  { name: "date", category: "fruit", fridgeDays: 180, freezerDays: 365, perishable: true, keywords: ["date", "dates"] },
  { name: "guava", category: "fruit", fridgeDays: 4, freezerDays: 240, perishable: true, keywords: ["guava"] },
  { name: "passion fruit", category: "fruit", fridgeDays: 14, freezerDays: 300, perishable: true, keywords: ["passion fruit", "passionfruit"] },
  { name: "papaya", category: "fruit", fridgeDays: 3, freezerDays: 240, perishable: true, keywords: ["papaya"] },
  { name: "lychee", category: "fruit", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["lychee", "litchi"] },
  { name: "persimmon", category: "fruit", fridgeDays: 5, freezerDays: 240, perishable: true, keywords: ["persimmon"] },
  { name: "tangerine", category: "fruit", fridgeDays: 14, freezerDays: 90, perishable: true, keywords: ["tangerine", "mandarin"] },

  // Vegetables
  { name: "carrot", category: "vegetable", fridgeDays: 28, freezerDays: 365, perishable: true, keywords: ["carrot", "carrots"] },
  { name: "broccoli", category: "vegetable", fridgeDays: 7, freezerDays: 365, perishable: true, keywords: ["broccoli", "brocolli"] },
  { name: "spinach", category: "vegetable", fridgeDays: 7, freezerDays: 300, perishable: true, keywords: ["spinach"] },
  { name: "lettuce", category: "vegetable", fridgeDays: 10, freezerDays: null, perishable: true, keywords: ["lettuce", "romaine", "iceberg"] },
  { name: "cucumber", category: "vegetable", fridgeDays: 14, freezerDays: null, perishable: true, keywords: ["cucumber", "cucumbers"] },
  { name: "bell pepper", category: "vegetable", fridgeDays: 14, freezerDays: 240, perishable: true, keywords: ["bell pepper", "capsicum", "pepper", "peppers"] },
  { name: "onion", category: "vegetable", fridgeDays: 60, freezerDays: 240, perishable: false, keywords: ["onion", "onions"] },
  { name: "garlic", category: "vegetable", fridgeDays: 90, freezerDays: 300, perishable: false, keywords: ["garlic"] },
  { name: "potato", category: "vegetable", fridgeDays: null, freezerDays: 300, perishable: false, keywords: ["potato", "potatoes"] },
  { name: "sweet potato", category: "vegetable", fridgeDays: null, freezerDays: 300, perishable: false, keywords: ["sweet potato", "yam"] },
  { name: "tomato", category: "vegetable", fridgeDays: 7, freezerDays: 240, perishable: true, keywords: ["tomato", "tomatoes"] },
  { name: "celery", category: "vegetable", fridgeDays: 28, freezerDays: 300, perishable: true, keywords: ["celery"] },
  { name: "mushroom", category: "vegetable", fridgeDays: 7, freezerDays: 300, perishable: true, keywords: ["mushroom", "mushrooms"] },
  { name: "corn", category: "vegetable", fridgeDays: 3, freezerDays: 365, perishable: true, keywords: ["corn", "corn on the cob"] },
  { name: "green beans", category: "vegetable", fridgeDays: 7, freezerDays: 365, perishable: true, keywords: ["green beans", "string beans"] },
  { name: "peas", category: "vegetable", fridgeDays: 5, freezerDays: 365, perishable: true, keywords: ["peas", "green peas"] },
  { name: "cauliflower", category: "vegetable", fridgeDays: 7, freezerDays: 300, perishable: true, keywords: ["cauliflower"] },
  { name: "asparagus", category: "vegetable", fridgeDays: 4, freezerDays: 300, perishable: true, keywords: ["asparagus"] },
  { name: "eggplant", category: "vegetable", fridgeDays: 7, freezerDays: 240, perishable: true, keywords: ["eggplant", "aubergine"] },
  { name: "zucchini", category: "vegetable", fridgeDays: 5, freezerDays: 300, perishable: true, keywords: ["zucchini", "courgette"] },
  { name: "cabbage", category: "vegetable", fridgeDays: 28, freezerDays: null, perishable: true, keywords: ["cabbage"] },
  { name: "kale", category: "vegetable", fridgeDays: 7, freezerDays: 240, perishable: true, keywords: ["kale"] },
  { name: "radish", category: "vegetable", fridgeDays: 14, freezerDays: null, perishable: true, keywords: ["radish", "radishes"] },
  { name: "beet", category: "vegetable", fridgeDays: 14, freezerDays: 240, perishable: true, keywords: ["beet", "beetroot", "beets"] },
  { name: "brussels sprout", category: "vegetable", fridgeDays: 10, freezerDays: 365, perishable: true, keywords: ["brussels sprout", "brussel sprout", "brussels sprouts"] },
  { name: "scallion", category: "vegetable", fridgeDays: 10, freezerDays: 60, perishable: true, keywords: ["scallion", "green onion", "spring onion"] },
  { name: "leek", category: "vegetable", fridgeDays: 14, freezerDays: 90, perishable: true, keywords: ["leek", "leeks"] },
  { name: "artichoke", category: "vegetable", fridgeDays: 7, freezerDays: 240, perishable: true, keywords: ["artichoke", "artichokes"] },
  { name: "pumpkin", category: "vegetable", fridgeDays: 90, freezerDays: 300, perishable: false, keywords: ["pumpkin"] },
  { name: "squash", category: "vegetable", fridgeDays: 14, freezerDays: 300, perishable: true, keywords: ["squash", "butternut squash", "spaghetti squash", "acorn squash"] },
  { name: "bok choy", category: "vegetable", fridgeDays: 7, freezerDays: null, perishable: true, keywords: ["bok choy", "pak choi"] },
  { name: "chard", category: "vegetable", fridgeDays: 5, freezerDays: 300, perishable: true, keywords: ["chard", "swiss chard"] },
  { name: "collard greens", category: "vegetable", fridgeDays: 5, freezerDays: 300, perishable: true, keywords: ["collard greens", "collards"] },
  { name: "fennel", category: "vegetable", fridgeDays: 10, freezerDays: 240, perishable: true, keywords: ["fennel"] },
  { name: "jicama", category: "vegetable", fridgeDays: 21, freezerDays: null, perishable: false, keywords: ["jicama"] },
  { name: "kohlrabi", category: "vegetable", fridgeDays: 21, freezerDays: 300, perishable: true, keywords: ["kohlrabi"] },
  { name: "okra", category: "vegetable", fridgeDays: 4, freezerDays: 270, perishable: true, keywords: ["okra"] },
  { name: "parsnip", category: "vegetable", fridgeDays: 28, freezerDays: 270, perishable: true, keywords: ["parsnip", "parsnips"] },
  { name: "rutabaga", category: "vegetable", fridgeDays: 30, freezerDays: 270, perishable: false, keywords: ["rutabaga"] },
  { name: "snow peas", category: "vegetable", fridgeDays: 7, freezerDays: 365, perishable: true, keywords: ["snow peas"] },
  { name: "sugar snap peas", category: "vegetable", fridgeDays: 7, freezerDays: 365, perishable: true, keywords: ["sugar snap peas", "snap peas"] },
  { name: "turnip", category: "vegetable", fridgeDays: 14, freezerDays: 270, perishable: true, keywords: ["turnip", "turnips"] },
  { name: "watercress", category: "vegetable", fridgeDays: 4, freezerDays: null, perishable: true, keywords: ["watercress"] },
  { name: "arugula", category: "vegetable", fridgeDays: 7, freezerDays: null, perishable: true, keywords: ["arugula", "rocket"] },
  { name: "endive", category: "vegetable", fridgeDays: 7, freezerDays: null, perishable: true, keywords: ["endive", "belgian endive"] },
  { name: "ginger", category: "vegetable", fridgeDays: 30, freezerDays: 180, perishable: true, keywords: ["ginger", "ginger root"] },
  { name: "chili pepper", category: "vegetable", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["chili pepper", "jalapeno", "habanero", "serrano"] },
  { name: "radicchio", category: "vegetable", fridgeDays: 7, freezerDays: null, perishable: true, keywords: ["radicchio"] },
  { name: "bean sprouts", category: "vegetable", fridgeDays: 3, freezerDays: null, perishable: true, keywords: ["bean sprouts", "mung bean sprouts"] },
  { name: "edamame", category: "vegetable", fridgeDays: 7, freezerDays: 365, perishable: true, keywords: ["edamame", "soybean"] },
  { name: "bamboo shoot", category: "vegetable", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["bamboo shoot", "bamboo shoots"] },
  { name: "water chestnut", category: "vegetable", fridgeDays: 10, freezerDays: 180, perishable: true, keywords: ["water chestnut", "water chestnuts"] },

  // Dairy
  { name: "milk", category: "dairy", fridgeDays: 7, freezerDays: 90, perishable: true, keywords: ["milk"] },
  { name: "cheddar cheese", category: "dairy", fridgeDays: 28, freezerDays: 180, perishable: true, keywords: ["cheddar", "cheddar cheese"] },
  { name: "mozzarella cheese", category: "dairy", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["mozzarella", "mozzarella cheese"] },
  { name: "parmesan cheese", category: "dairy", fridgeDays: 180, freezerDays: 180, perishable: true, keywords: ["parmesan", "parmesan cheese"] },
  { name: "feta cheese", category: "dairy", fridgeDays: 30, freezerDays: 180, perishable: true, keywords: ["feta", "feta cheese"] },
  { name: "goat cheese", category: "dairy", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["goat cheese", "chèvre"] },
  { name: "blue cheese", category: "dairy", fridgeDays: 21, freezerDays: 180, perishable: true, keywords: ["blue cheese", "bleu cheese"] },
  { name: "butter", category: "dairy", fridgeDays: 90, freezerDays: 270, perishable: true, keywords: ["butter"] },
  { name: "yogurt", category: "dairy", fridgeDays: 14, freezerDays: 60, perishable: true, keywords: ["yogurt", "yoghurt"] },
  { name: "cream cheese", category: "dairy", fridgeDays: 14, freezerDays: 120, perishable: true, keywords: ["cream cheese", "philadelphia cream cheese"] },
  { name: "sour cream", category: "dairy", fridgeDays: 21, freezerDays: null, perishable: true, keywords: ["sour cream"] },
  { name: "cottage cheese", category: "dairy", fridgeDays: 10, freezerDays: 60, perishable: true, keywords: ["cottage cheese"] },
  { name: "heavy cream", category: "dairy", fridgeDays: 7, freezerDays: 120, perishable: true, keywords: ["heavy cream", "whipping cream"] },
  { name: "half-and-half", category: "dairy", fridgeDays: 7, freezerDays: 120, perishable: true, keywords: ["half-and-half", "half & half"] },
  { name: "eggs", category: "dairy", fridgeDays: 28, freezerDays: 365, perishable: true, keywords: ["egg", "eggs"] },
  { name: "ghee", category: "dairy", fridgeDays: 90, freezerDays: 365, perishable: false, keywords: ["ghee", "clarified butter"] },
  { name: "kefir", category: "dairy", fridgeDays: 10, freezerDays: 60, perishable: true, keywords: ["kefir"] },
  { name: "buttermilk", category: "dairy", fridgeDays: 14, freezerDays: 90, perishable: true, keywords: ["buttermilk"] },
  { name: "ricotta cheese", category: "dairy", fridgeDays: 7, freezerDays: 120, perishable: true, keywords: ["ricotta", "ricotta cheese"] },
  { name: "provolone cheese", category: "dairy", fridgeDays: 21, freezerDays: 180, perishable: true, keywords: ["provolone", "provolone cheese"] },
  { name: "swiss cheese", category: "dairy", fridgeDays: 28, freezerDays: 180, perishable: true, keywords: ["swiss", "swiss cheese"] },
  { name: "brie", category: "dairy", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["brie", "brie cheese"] },
  { name: "camembert", category: "dairy", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["camembert", "camembert cheese"] },
  { name: "colby cheese", category: "dairy", fridgeDays: 21, freezerDays: 120, perishable: true, keywords: ["colby", "colby cheese"] },
  { name: "colby-jack cheese", category: "dairy", fridgeDays: 21, freezerDays: 120, perishable: true, keywords: ["colby-jack", "colby jack"] },
  { name: "monterey jack cheese", category: "dairy", fridgeDays: 21, freezerDays: 120, perishable: true, keywords: ["monterey jack", "jack cheese"] },
  { name: "pepper jack cheese", category: "dairy", fridgeDays: 21, freezerDays: 120, perishable: true, keywords: ["pepper jack", "pepper jack cheese"] },
  { name: "muenster cheese", category: "dairy", fridgeDays: 14, freezerDays: 120, perishable: true, keywords: ["muenster", "muenster cheese"] },
  { name: "havarti cheese", category: "dairy", fridgeDays: 14, freezerDays: 120, perishable: true, keywords: ["havarti", "havarti cheese"] },
  { name: "gouda cheese", category: "dairy", fridgeDays: 21, freezerDays: 180, perishable: true, keywords: ["gouda", "gouda cheese"] },
  { name: "gruyère cheese", category: "dairy", fridgeDays: 28, freezerDays: 180, perishable: true, keywords: ["gruyere", "gruyère"] },
  { name: "asiago cheese", category: "dairy", fridgeDays: 90, freezerDays: 180, perishable: true, keywords: ["asiago", "asiago cheese"] },
  { name: "romano cheese", category: "dairy", fridgeDays: 120, freezerDays: 180, perishable: true, keywords: ["romano", "pecorino romano"] },
  { name: "mascarpone", category: "dairy", fridgeDays: 5, freezerDays: 60, perishable: true, keywords: ["mascarpone"] },
  { name: "crème fraîche", category: "dairy", fridgeDays: 10, freezerDays: null, perishable: true, keywords: ["creme fraiche", "crème fraîche"] },
  { name: "paneer", category: "dairy", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["paneer"] },
  { name: "halloumi", category: "dairy", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["halloumi"] },
  { name: "queso fresco", category: "dairy", fridgeDays: 14, freezerDays: 60, perishable: true, keywords: ["queso fresco"] },
  { name: "cotija cheese", category: "dairy", fridgeDays: 30, freezerDays: 180, perishable: true, keywords: ["cotija", "cotija cheese"] },

  // Meat
  { name: "ground beef", category: "meat", fridgeDays: 2, freezerDays: 120, perishable: true, keywords: ["ground beef", "mince", "beef mince"] },
  { name: "steak", category: "meat", fridgeDays: 4, freezerDays: 270, perishable: true, keywords: ["steak", "beef steak"] },
  { name: "beef roast", category: "meat", fridgeDays: 4, freezerDays: 270, perishable: true, keywords: ["beef roast"] },
  { name: "pork chop", category: "meat", fridgeDays: 4, freezerDays: 180, perishable: true, keywords: ["pork chop", "pork chops"] },
  { name: "pork roast", category: "meat", fridgeDays: 4, freezerDays: 180, perishable: true, keywords: ["pork roast"] },
  { name: "bacon", category: "meat", fridgeDays: 7, freezerDays: 120, perishable: true, keywords: ["bacon"] },
  { name: "sausage", category: "meat", fridgeDays: 2, freezerDays: 60, perishable: true, keywords: ["sausage", "sausages", "pork sausage"] },
  { name: "ham", category: "meat", fridgeDays: 5, freezerDays: 60, perishable: true, keywords: ["ham", "cooked ham"] },
  { name: "lamb", category: "meat", fridgeDays: 4, freezerDays: 270, perishable: true, keywords: ["lamb", "lamb chops"] },
  { name: "veal", category: "meat", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["veal"] },
  { name: "hot dog", category: "meat", fridgeDays: 7, freezerDays: 60, perishable: true, keywords: ["hot dog", "hot dogs", "frankfurter", "weiner"] },
  { name: "pepperoni", category: "meat", fridgeDays: 21, freezerDays: 180, perishable: true, keywords: ["pepperoni"] },
  { name: "chorizo", category: "meat", fridgeDays: 7, freezerDays: 60, perishable: true, keywords: ["chorizo"] },
  { name: "salami", category: "meat", fridgeDays: 21, freezerDays: 60, perishable: true, keywords: ["salami", "genoa salami"] },
  { name: "prosciutto", category: "meat", fridgeDays: 5, freezerDays: 30, perishable: true, keywords: ["prosciutto"] },
  { name: "ground pork", category: "meat", fridgeDays: 2, freezerDays: 120, perishable: true, keywords: ["ground pork", "pork mince"] },
  { name: "ground lamb", category: "meat", fridgeDays: 2, freezerDays: 120, perishable: true, keywords: ["ground lamb", "lamb mince"] },
  { name: "bratwurst", category: "meat", fridgeDays: 2, freezerDays: 60, perishable: true, keywords: ["bratwurst", "brats"] },
  { name: "italian sausage", category: "meat", fridgeDays: 2, freezerDays: 60, perishable: true, keywords: ["italian sausage"] },
  { name: "corned beef", category: "meat", fridgeDays: 7, freezerDays: 30, perishable: true, keywords: ["corned beef"] },
  { name: "liver", category: "meat", fridgeDays: 2, freezerDays: 120, perishable: true, keywords: ["liver", "beef liver", "chicken liver"] },
  { name: "oxtail", category: "meat", fridgeDays: 3, freezerDays: 270, perishable: true, keywords: ["oxtail"] },
  { name: "pancetta", category: "meat", fridgeDays: 14, freezerDays: 90, perishable: true, keywords: ["pancetta"] },
  { name: "canadian bacon", category: "meat", fridgeDays: 5, freezerDays: 45, perishable: true, keywords: ["canadian bacon", "back bacon"] },
  { name: "kielbasa", category: "meat", fridgeDays: 7, freezerDays: 60, perishable: true, keywords: ["kielbasa", "polish sausage"] },

  // Deli
  { name: "sliced turkey", category: "deli", fridgeDays: 5, freezerDays: 60, perishable: true, keywords: ["sliced turkey", "turkey breast", "deli turkey"] },
  { name: "sliced ham", category: "deli", fridgeDays: 5, freezerDays: 60, perishable: true, keywords: ["sliced ham", "deli ham"] },
  { name: "sliced roast beef", category: "deli", fridgeDays: 5, freezerDays: 60, perishable: true, keywords: ["sliced roast beef", "deli roast beef"] },
  { name: "sliced chicken", category: "deli", fridgeDays: 5, freezerDays: 60, perishable: true, keywords: ["sliced chicken", "chicken breast", "deli chicken"] },
  { name: "pastrami", category: "deli", fridgeDays: 5, freezerDays: 60, perishable: true, keywords: ["pastrami"] },
  { name: "bologna", category: "deli", fridgeDays: 7, freezerDays: 60, perishable: true, keywords: ["bologna", "baloney"] },
  { name: "liverwurst", category: "deli", fridgeDays: 7, freezerDays: 60, perishable: true, keywords: ["liverwurst", "braunschweiger"] },
  { name: "mortadella", category: "deli", fridgeDays: 7, freezerDays: 60, perishable: true, keywords: ["mortadella"] },
  { name: "capocollo", category: "deli", fridgeDays: 28, freezerDays: 60, perishable: true, keywords: ["capocollo", "coppa", "capicola"] },
  { name: "soppressata", category: "deli", fridgeDays: 28, freezerDays: 60, perishable: true, keywords: ["soppressata"] },
  { name: "head cheese", category: "deli", fridgeDays: 7, freezerDays: 60, perishable: true, keywords: ["head cheese"] },
  { name: "potato salad", category: "deli", fridgeDays: 4, freezerDays: null, perishable: true, keywords: ["potato salad"] },
  { name: "macaroni salad", category: "deli", fridgeDays: 4, freezerDays: null, perishable: true, keywords: ["macaroni salad"] },
  { name: "coleslaw", category: "deli", fridgeDays: 4, freezerDays: null, perishable: true, keywords: ["coleslaw", "slaw"] },
  { name: "chicken salad", category: "deli", fridgeDays: 4, freezerDays: null, perishable: true, keywords: ["chicken salad"] },
  { name: "tuna salad", category: "deli", fridgeDays: 4, freezerDays: null, perishable: true, keywords: ["tuna salad"] },
  { name: "egg salad", category: "deli", fridgeDays: 4, freezerDays: null, perishable: true, keywords: ["egg salad"] },

  // Seafood
  { name: "salmon", category: "seafood", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["salmon", "salmon fillet"] },
  { name: "tuna", category: "seafood", fridgeDays: 2, freezerDays: 90, perishable: true, keywords: ["tuna", "tuna steak"] },
  { name: "shrimp", category: "seafood", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["shrimp", "prawns"] },
  { name: "cod", category: "seafood", fridgeDays: 2, freezerDays: 240, perishable: true, keywords: ["cod"] },
  { name: "tilapia", category: "seafood", fridgeDays: 2, freezerDays: 240, perishable: true, keywords: ["tilapia"] },
  { name: "halibut", category: "seafood", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["halibut"] },
  { name: "crab", category: "seafood", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["crab", "crab meat", "king crab", "dungeness crab"] },
  { name: "lobster", category: "seafood", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["lobster"] },
  { name: "scallops", category: "seafood", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["scallop", "scallops"] },
  { name: "clams", category: "seafood", fridgeDays: 2, freezerDays: 90, perishable: true, keywords: ["clam", "clams"] },
  { name: "mussels", category: "seafood", fridgeDays: 2, freezerDays: 90, perishable: true, keywords: ["mussel", "mussels"] },
  { name: "oysters", category: "seafood", fridgeDays: 2, freezerDays: 90, perishable: true, keywords: ["oyster", "oysters"] },
  { name: "sushi", category: "seafood", fridgeDays: 1, freezerDays: null, perishable: true, keywords: ["sushi", "sashimi"] },
  { name: "smoked salmon", category: "seafood", fridgeDays: 7, freezerDays: 120, perishable: true, keywords: ["smoked salmon", "lox"] },
  { name: "trout", category: "seafood", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["trout", "rainbow trout"] },
  { name: "mahi-mahi", category: "seafood", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["mahi-mahi", "mahi mahi"] },
  { name: "swordfish", category: "seafood", fridgeDays: 2, freezerDays: 120, perishable: true, keywords: ["swordfish"] },
  { name: "calamari", category: "seafood", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["calamari", "squid"] },
  { name: "octopus", category: "seafood", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["octopus"] },
  { name: "anchovies", category: "seafood", fridgeDays: 30, freezerDays: 90, perishable: false, keywords: ["anchovy", "anchovies"] },
  { name: "sardines", category: "seafood", fridgeDays: 5, freezerDays: 60, perishable: false, keywords: ["sardine", "sardines"] },
  { name: "caviar", category: "seafood", fridgeDays: 14, freezerDays: 30, perishable: true, keywords: ["caviar"] },
  { name: "crawfish", category: "seafood", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["crawfish", "crayfish", "mudbugs"] },
  { name: "sea bass", category: "seafood", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["sea bass"] },
  { name: "snapper", category: "seafood", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["snapper", "red snapper"] },
  { name: "grouper", category: "seafood", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["grouper"] },
  { name: "catfish", category: "seafood", fridgeDays: 2, freezerDays: 240, perishable: true, keywords: ["catfish"] },
  { name: "haddock", category: "seafood", fridgeDays: 2, freezerDays: 240, perishable: true, keywords: ["haddock"] },
  { name: "pollock", category: "seafood", fridgeDays: 2, freezerDays: 240, perishable: true, keywords: ["pollock"] },
  { name: "mackerel", category: "seafood", fridgeDays: 2, freezerDays: 90, perishable: true, keywords: ["mackerel"] },
  { name: "herring", category: "seafood", fridgeDays: 3, freezerDays: 180, perishable: true, keywords: ["herring", "pickled herring"] },
  { name: "surimi", category: "seafood", fridgeDays: 3, freezerDays: 180, perishable: true, keywords: ["surimi", "imitation crab"] },

  // Poultry
  { name: "chicken breast", category: "poultry", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["chicken breast", "chicken breasts"] },
  { name: "chicken thigh", category: "poultry", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["chicken thigh", "chicken thighs"] },
  { name: "whole chicken", category: "poultry", fridgeDays: 2, freezerDays: 365, perishable: true, keywords: ["whole chicken", "roasting chicken"] },
  { name: "ground chicken", category: "poultry", fridgeDays: 2, freezerDays: 120, perishable: true, keywords: ["ground chicken", "chicken mince"] },
  { name: "turkey", category: "poultry", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["turkey", "turkey breast"] },
  { name: "ground turkey", category: "poultry", fridgeDays: 2, freezerDays: 120, perishable: true, keywords: ["ground turkey", "turkey mince"] },
  { name: "duck", category: "poultry", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["duck"] },
  { name: "chicken wings", category: "poultry", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["chicken wings", "wings"] },
  { name: "chicken drumsticks", category: "poultry", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["chicken drumsticks", "drumsticks"] },
  { name: "rotisserie chicken", category: "poultry", fridgeDays: 4, freezerDays: 120, perishable: true, keywords: ["rotisserie chicken"] },
  { name: "chicken sausage", category: "poultry", fridgeDays: 2, freezerDays: 60, perishable: true, keywords: ["chicken sausage"] },
  { name: "turkey sausage", category: "poultry", fridgeDays: 2, freezerDays: 60, perishable: true, keywords: ["turkey sausage"] },
  { name: "turkey bacon", category: "poultry", fridgeDays: 7, freezerDays: 120, perishable: true, keywords: ["turkey bacon"] },
  { name: "cornish hen", category: "poultry", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["cornish hen"] },
  { name: "quail", category: "poultry", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["quail"] },
  { name: "goose", category: "poultry", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["goose"] },
  { name: "pheasant", category: "poultry", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["pheasant"] },
  { name: "duck eggs", category: "poultry", fridgeDays: 42, freezerDays: null, perishable: true, keywords: ["duck egg", "duck eggs"] },
  { name: "quail eggs", category: "poultry", fridgeDays: 42, freezerDays: null, perishable: true, keywords: ["quail egg", "quail eggs"] },

  // Pantry
  { name: "all-purpose flour", category: "pantry", fridgeDays: null, freezerDays: 730, perishable: false, keywords: ["flour", "all purpose flour", "plain flour"] },
  { name: "whole wheat flour", category: "pantry", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["whole wheat flour"] },
  { name: "granulated sugar", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["sugar", "white sugar", "granulated sugar"] },
  { name: "brown sugar", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["brown sugar"] },
  { name: "powdered sugar", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["powdered sugar", "confectioners sugar", "icing sugar"] },
  { name: "baking soda", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["baking soda", "bicarbonate of soda"] },
  { name: "baking powder", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["baking powder"] },
  { name: "salt", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["salt", "table salt", "sea salt"] },
  { name: "pasta", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["pasta", "spaghetti", "penne", "macaroni", "fettuccine", "linguine", "rigatoni", "rotini"] },
  { name: "white rice", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["white rice", "rice", "jasmine rice", "basmati rice"] },
  { name: "brown rice", category: "pantry", fridgeDays: 180, freezerDays: 180, perishable: false, keywords: ["brown rice"] },
  { name: "canned tomatoes", category: "pantry", fridgeDays: 5, freezerDays: 60, perishable: false, keywords: ["canned tomatoes", "tinned tomatoes"] },
  { name: "canned beans", category: "pantry", fridgeDays: 4, freezerDays: 60, perishable: false, keywords: ["canned beans", "tinned beans", "kidney beans", "black beans", "chickpeas", "pinto beans", "frijoles"] },
  { name: "canned corn", category: "pantry", fridgeDays: 4, freezerDays: 60, perishable: false, keywords: ["canned corn", "tinned corn", "sweet corn"] },
  { name: "canned tuna", category: "pantry", fridgeDays: 4, freezerDays: 60, perishable: false, keywords: ["canned tuna", "tinned tuna"] },
  { name: "peanut butter", category: "pantry", fridgeDays: 90, freezerDays: null, perishable: false, keywords: ["peanut butter", "pb"] },
  { name: "jam", category: "pantry", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["jam", "jelly", "preserves"] },
  { name: "honey", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["honey"] },
  { name: "maple syrup", category: "pantry", fridgeDays: 365, freezerDays: null, perishable: false, keywords: ["maple syrup"] },
  { name: "oats", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["oats", "oatmeal", "rolled oats", "steel cut oats"] },
  { name: "cereal", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cereal", "breakfast cereal", "corn flakes", "cheerios", "frosted flakes"] },
  { name: "bread crumbs", category: "pantry", fridgeDays: 180, freezerDays: 180, perishable: false, keywords: ["breadcrumbs", "bread crumbs", "panko"] },
  { name: "crackers", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["crackers", "saltines", "ritz"] },
  { name: "popcorn kernels", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["popcorn kernels", "popcorn"] },
  { name: "coffee beans", category: "pantry", fridgeDays: null, freezerDays: 180, perishable: false, keywords: ["coffee beans", "coffee"] },
  { name: "ground coffee", category: "pantry", fridgeDays: null, freezerDays: 180, perishable: false, keywords: ["ground coffee"] },
  { name: "tea bags", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["tea bags", "tea", "green tea", "black tea"] },
  { name: "cocoa powder", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cocoa powder", "cacao powder"] },
  { name: "chocolate chips", category: "pantry", fridgeDays: null, freezerDays: 730, perishable: false, keywords: ["chocolate chips"] },
  { name: "vanilla extract", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["vanilla extract"] },
  { name: "lentils", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["lentils", "lentil", "red lentils", "green lentils"] },
  { name: "dried beans", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["dried beans"] },
  { name: "bouillon cubes", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["bouillon cubes", "stock cubes"] },
  { name: "broth", category: "pantry", fridgeDays: 5, freezerDays: 180, perishable: false, keywords: ["broth", "stock", "chicken broth", "beef broth", "vegetable broth"] },
  { name: "coconut milk", category: "pantry", fridgeDays: 7, freezerDays: 90, perishable: false, keywords: ["coconut milk"] },
  { name: "evaporated milk", category: "pantry", fridgeDays: 5, freezerDays: 90, perishable: false, keywords: ["evaporated milk"] },
  { name: "sweetened condensed milk", category: "pantry", fridgeDays: 14, freezerDays: 90, perishable: false, keywords: ["condensed milk", "sweetened condensed milk"] },
  { name: "gelatin", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["gelatin", "jello"] },
  { name: "cornstarch", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cornstarch", "corn flour"] },
  { name: "cornmeal", category: "pantry", fridgeDays: 365, freezerDays: 730, perishable: false, keywords: ["cornmeal"] },
  { name: "yeast", category: "pantry", fridgeDays: 120, freezerDays: 180, perishable: false, keywords: ["yeast", "active dry yeast", "instant yeast"] },
  { name: "pickles", category: "pantry", fridgeDays: 90, freezerDays: null, perishable: false, keywords: ["pickles", "gherkins"] },
  { name: "olives", category: "pantry", fridgeDays: 21, freezerDays: null, perishable: false, keywords: ["olives", "kalamata", "green olives"] },
  { name: "capers", category: "pantry", fridgeDays: 365, freezerDays: null, perishable: false, keywords: ["capers"] },
  { name: "sundried tomatoes", category: "pantry", fridgeDays: 21, freezerDays: 180, perishable: false, keywords: ["sundried tomatoes", "sun-dried tomatoes"] },
  { name: "canned soup", category: "pantry", fridgeDays: 4, freezerDays: 60, perishable: false, keywords: ["canned soup", "soup"] },
  { name: "instant noodles", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["instant noodles", "ramen"] },
  { name: "seaweed", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["seaweed", "nori", "kombu", "wakame"] },
  { name: "protein powder", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["protein powder", "whey protein", "vegan protein"] },
  { name: "apple sauce", category: "pantry", fridgeDays: 10, freezerDays: 60, perishable: false, keywords: ["apple sauce", "applesauce"] },
  { name: "marshmallows", category: "pantry", fridgeDays: null, freezerDays: 120, perishable: false, keywords: ["marshmallows"] },
  { name: "agave nectar", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["agave nectar", "agave syrup"] },
  { name: "molasses", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["molasses", "blackstrap molasses"] },
  { name: "corn syrup", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["corn syrup", "karo syrup"] },
  { name: "almond flour", category: "pantry", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["almond flour", "almond meal"] },
  { name: "coconut flour", category: "pantry", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["coconut flour"] },
  { name: "tapioca starch", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["tapioca starch", "tapioca flour"] },
  { name: "arrowroot powder", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["arrowroot powder", "arrowroot starch"] },
  { name: "potato starch", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["potato starch"] },
  { name: "wild rice", category: "pantry", fridgeDays: 180, freezerDays: 180, perishable: false, keywords: ["wild rice"] },
  { name: "arborio rice", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["arborio rice"] },
  { name: "sushi rice", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["sushi rice", "calrose rice"] },
  { name: "semolina", category: "pantry", fridgeDays: 365, freezerDays: 730, perishable: false, keywords: ["semolina"] },
  { name: "nutritional yeast", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["nutritional yeast", "nooch"] },
  { name: "xanthan gum", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["xanthan gum"] },
  { name: "guar gum", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["guar gum"] },
  { name: "cream of tartar", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cream of tartar"] },
  { name: "canned salmon", category: "pantry", fridgeDays: 4, freezerDays: 60, perishable: false, keywords: ["canned salmon", "tinned salmon"] },
  { name: "canned chicken", category: "pantry", fridgeDays: 4, freezerDays: 60, perishable: false, keywords: ["canned chicken", "tinned chicken"] },
  { name: "canned fruit", category: "pantry", fridgeDays: 7, freezerDays: 60, perishable: false, keywords: ["canned fruit", "canned peaches", "canned pears"] },
  { name: "canned vegetables", category: "pantry", fridgeDays: 4, freezerDays: 60, perishable: false, keywords: ["canned vegetables", "canned green beans"] },
  { name: "canned chili", category: "pantry", fridgeDays: 4, freezerDays: 60, perishable: false, keywords: ["canned chili", "chili"] },
  { name: "canned ravioli", category: "pantry", fridgeDays: 4, freezerDays: 60, perishable: false, keywords: ["canned ravioli", "chef boyardee"] },
  { name: "canned spam", category: "pantry", fridgeDays: 5, freezerDays: 60, perishable: false, keywords: ["spam", "canned meat"] },

  // Frozen
  { name: "frozen vegetables", category: "frozen", fridgeDays: null, freezerDays: 365, perishable: false, keywords: ["frozen vegetables", "frozen peas", "frozen corn"] },
  { name: "frozen fruit", category: "frozen", fridgeDays: null, freezerDays: 300, perishable: false, keywords: ["frozen fruit", "frozen berries"] },
  { name: "ice cream", category: "frozen", fridgeDays: null, freezerDays: 90, perishable: true, keywords: ["ice cream", "gelato", "sorbet"] },
  { name: "frozen pizza", category: "frozen", fridgeDays: null, freezerDays: 365, perishable: false, keywords: ["frozen pizza"] },
  { name: "frozen dinner", category: "frozen", fridgeDays: null, freezerDays: 365, perishable: false, keywords: ["frozen dinner", "tv dinner", "frozen meal"] },
  { name: "frozen waffles", category: "frozen", fridgeDays: null, freezerDays: 180, perishable: false, keywords: ["frozen waffles", "waffles"] },
  { name: "frozen french fries", category: "frozen", fridgeDays: null, freezerDays: 365, perishable: false, keywords: ["frozen french fries", "frozen fries", "frozen chips"] },
  { name: "frozen fish fillets", category: "frozen", fridgeDays: null, freezerDays: 240, perishable: true, keywords: ["frozen fish", "frozen fish fillets"] },
  { name: "frozen chicken nuggets", category: "frozen", fridgeDays: null, freezerDays: 180, perishable: true, keywords: ["frozen chicken nuggets", "chicken nuggets"] },
  { name: "ice", category: "frozen", fridgeDays: null, freezerDays: null, perishable: true, keywords: ["ice", "ice cubes"] },
  { name: "frozen burrito", category: "frozen", fridgeDays: 1, freezerDays: 90, perishable: false, keywords: ["frozen burrito"] },
  { name: "frozen spring rolls", category: "frozen", fridgeDays: 1, freezerDays: 180, perishable: false, keywords: ["frozen spring rolls", "egg rolls"] },
  { name: "frozen dumplings", category: "frozen", fridgeDays: 1, freezerDays: 180, perishable: false, keywords: ["frozen dumplings", "potstickers", "gyoza"] },
  { name: "frozen burger patties", category: "frozen", fridgeDays: 1, freezerDays: 120, perishable: true, keywords: ["frozen burger", "frozen patties"] },
  { name: "frozen pizza rolls", category: "frozen", fridgeDays: 1, freezerDays: 180, perishable: false, keywords: ["pizza rolls", "totino's pizza rolls"] },
  { name: "frozen hot pockets", category: "frozen", fridgeDays: 1, freezerDays: 180, perishable: false, keywords: ["hot pockets"] },
  { name: "frozen corn dogs", category: "frozen", fridgeDays: 1, freezerDays: 180, perishable: false, keywords: ["corn dogs"] },
  { name: "frozen tater tots", category: "frozen", fridgeDays: null, freezerDays: 365, perishable: false, keywords: ["tater tots", "potato puffs"] },
  { name: "frozen hash browns", category: "frozen", fridgeDays: null, freezerDays: 365, perishable: false, keywords: ["hash browns"] },
  { name: "frozen onion rings", category: "frozen", fridgeDays: null, freezerDays: 365, perishable: false, keywords: ["onion rings"] },
  { name: "frozen garlic bread", category: "frozen", fridgeDays: null, freezerDays: 180, perishable: false, keywords: ["frozen garlic bread"] },
  { name: "frozen meatballs", category: "frozen", fridgeDays: 1, freezerDays: 120, perishable: true, keywords: ["frozen meatballs"] },
  { name: "frozen edamame", category: "frozen", fridgeDays: 1, freezerDays: 365, perishable: true, keywords: ["frozen edamame"] },
  { name: "frozen yogurt", category: "frozen", fridgeDays: null, freezerDays: 60, perishable: true, keywords: ["frozen yogurt", "froyo"] },
  { name: "cool whip", category: "frozen", fridgeDays: 14, freezerDays: 90, perishable: true, keywords: ["cool whip", "whipped topping"] },
  { name: "sherbet", category: "frozen", fridgeDays: null, freezerDays: 90, perishable: true, keywords: ["sherbet"] },
  { name: "ice cream sandwich", category: "frozen", fridgeDays: null, freezerDays: 90, perishable: true, keywords: ["ice cream sandwich"] },
  { name: "popsicle", category: "frozen", fridgeDays: null, freezerDays: 240, perishable: false, keywords: ["popsicle", "ice pop", "ice lolly"] },
  { name: "fudgesicle", category: "frozen", fridgeDays: null, freezerDays: 180, perishable: false, keywords: ["fudgesicle"] },

  // Bakery
  { name: "bread", category: "bakery", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["bread", "sliced bread", "loaf of bread"] },
  { name: "bagels", category: "bakery", fridgeDays: 7, freezerDays: 120, perishable: true, keywords: ["bagel", "bagels"] },
  { name: "croissants", category: "bakery", fridgeDays: 2, freezerDays: 60, perishable: true, keywords: ["croissant", "croissants"] },
  { name: "muffins", category: "bakery", fridgeDays: 3, freezerDays: 90, perishable: true, keywords: ["muffin", "muffins"] },
  { name: "cake", category: "bakery", fridgeDays: 5, freezerDays: 120, perishable: true, keywords: ["cake", "birthday cake"] },
  { name: "cookies", category: "bakery", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["cookie", "cookies", "oreo"] },
  { name: "pie", category: "bakery", fridgeDays: 4, freezerDays: 180, perishable: true, keywords: ["pie", "apple pie", "pumpkin pie"] },
  { name: "donuts", category: "bakery", fridgeDays: 2, freezerDays: 90, perishable: true, keywords: ["donut", "donuts", "doughnut"] },
  { name: "tortillas", category: "bakery", fridgeDays: 21, freezerDays: 180, perishable: true, keywords: ["tortillas", "flour tortillas", "corn tortillas"] },
  { name: "pita bread", category: "bakery", fridgeDays: 7, freezerDays: 90, perishable: true, keywords: ["pita", "pita bread"] },
  { name: "naan", category: "bakery", fridgeDays: 4, freezerDays: 90, perishable: true, keywords: ["naan", "naan bread"] },
  { name: "english muffins", category: "bakery", fridgeDays: 7, freezerDays: 90, perishable: true, keywords: ["english muffin", "english muffins"] },
  { name: "sourdough bread", category: "bakery", fridgeDays: 10, freezerDays: 180, perishable: true, keywords: ["sourdough", "sourdough bread"] },
  { name: "baguette", category: "bakery", fridgeDays: 2, freezerDays: 90, perishable: true, keywords: ["baguette", "french bread"] },
  { name: "rye bread", category: "bakery", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["rye bread"] },
  { name: "pumpernickel bread", category: "bakery", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["pumpernickel"] },
  { name: "ciabatta", category: "bakery", fridgeDays: 3, freezerDays: 120, perishable: true, keywords: ["ciabatta"] },
  { name: "focaccia", category: "bakery", fridgeDays: 3, freezerDays: 120, perishable: true, keywords: ["focaccia"] },
  { name: "brioche", category: "bakery", fridgeDays: 5, freezerDays: 90, perishable: true, keywords: ["brioche"] },
  { name: "challah", category: "bakery", fridgeDays: 5, freezerDays: 90, perishable: true, keywords: ["challah"] },
  { name: "cinnamon roll", category: "bakery", fridgeDays: 3, freezerDays: 90, perishable: true, keywords: ["cinnamon roll", "cinnamon bun"] },
  { name: "scones", category: "bakery", fridgeDays: 3, freezerDays: 90, perishable: true, keywords: ["scone", "scones"] },
  { name: "biscotti", category: "bakery", fridgeDays: 30, freezerDays: 180, perishable: false, keywords: ["biscotti"] },
  { name: "brownies", category: "bakery", fridgeDays: 5, freezerDays: 90, perishable: true, keywords: ["brownie", "brownies"] },
  { name: "cupcakes", category: "bakery", fridgeDays: 3, freezerDays: 90, perishable: true, keywords: ["cupcake", "cupcakes"] },
  { name: "cheesecake", category: "bakery", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["cheesecake"] },
  { name: "pastry", category: "bakery", fridgeDays: 2, freezerDays: 60, perishable: true, keywords: ["pastry", "danish"] },
  { name: "pizza dough", category: "bakery", fridgeDays: 3, freezerDays: 90, perishable: true, keywords: ["pizza dough", "pizza base"] },

  // Condiments
  { name: "ketchup", category: "condiment", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["ketchup", "tomato ketchup"] },
  { name: "mustard", category: "condiment", fridgeDays: 365, freezerDays: null, perishable: false, keywords: ["mustard", "dijon mustard", "yellow mustard"] },
  { name: "mayonnaise", category: "condiment", fridgeDays: 60, freezerDays: null, perishable: true, keywords: ["mayonnaise", "mayo"] },
  { name: "relish", category: "condiment", fridgeDays: 270, freezerDays: null, perishable: false, keywords: ["relish", "pickle relish"] },
  { name: "bbq sauce", category: "condiment", fridgeDays: 120, freezerDays: null, perishable: false, keywords: ["bbq sauce", "barbecue sauce"] },
  { name: "soy sauce", category: "condiment", fridgeDays: 730, freezerDays: null, perishable: false, keywords: ["soy sauce", "shoyu", "tamari"] },
  { name: "hot sauce", category: "condiment", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["hot sauce", "sriracha", "tabasco", "cholula", "chili sauce"] },
  { name: "salad dressing", category: "condiment", fridgeDays: 90, freezerDays: null, perishable: true, keywords: ["salad dressing", "ranch", "italian dressing", "vinaigrette"] },
  { name: "vinegar", category: "condiment", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["vinegar", "apple cider vinegar", "white vinegar", "balsamic vinegar", "rice vinegar"] },
  { name: "worcestershire sauce", category: "condiment", fridgeDays: 365, freezerDays: null, perishable: false, keywords: ["worcestershire sauce"] },
  { name: "fish sauce", category: "condiment", fridgeDays: 365, freezerDays: null, perishable: false, keywords: ["fish sauce"] },
  { name: "oyster sauce", category: "condiment", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["oyster sauce"] },
  { name: "hoisin sauce", category: "condiment", fridgeDays: 90, freezerDays: null, perishable: false, keywords: ["hoisin sauce"] },
  { name: "tahini", category: "condiment", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["tahini"] },
  { name: "miso paste", category: "condiment", fridgeDays: 365, freezerDays: null, perishable: true, keywords: ["miso", "miso paste"] },
  { name: "gochujang", category: "condiment", fridgeDays: 365, freezerDays: null, perishable: true, keywords: ["gochujang", "korean chili paste"] },
  { name: "sambal oelek", category: "condiment", fridgeDays: 270, freezerDays: null, perishable: false, keywords: ["sambal oelek", "sambal"] },
  { name: "harissa", category: "condiment", fridgeDays: 30, freezerDays: 180, perishable: true, keywords: ["harissa"] },
  { name: "chili oil", category: "condiment", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["chili oil", "chili crisp"] },
  { name: "sesame paste", category: "condiment", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["sesame paste", "chinese sesame paste"] },
  { name: "duck sauce", category: "condiment", fridgeDays: 90, freezerDays: null, perishable: false, keywords: ["duck sauce", "plum sauce"] },
  { name: "sweet and sour sauce", category: "condiment", fridgeDays: 90, freezerDays: null, perishable: false, keywords: ["sweet and sour sauce"] },
  { name: "tartar sauce", category: "condiment", fridgeDays: 180, freezerDays: null, perishable: true, keywords: ["tartar sauce", "tartare sauce"] },
  { name: "cocktail sauce", category: "condiment", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["cocktail sauce"] },
  { name: "steak sauce", category: "condiment", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["steak sauce", "a1 sauce"] },
  { name: "horseradish", category: "condiment", fridgeDays: 120, freezerDays: null, perishable: true, keywords: ["horseradish", "prepared horseradish"] },
  { name: "wasabi", category: "condiment", fridgeDays: 30, freezerDays: 180, perishable: true, keywords: ["wasabi"] },
  { name: "mirin", category: "condiment", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["mirin", "sweet cooking wine"] },
  { name: "rice wine", category: "condiment", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["rice wine", "shaoxing wine"] },

  // Beverages
  { name: "water", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["water", "bottled water", "mineral water"] },
  { name: "orange juice", category: "beverage", fridgeDays: 10, freezerDays: 240, perishable: true, keywords: ["orange juice", "oj"] },
  { name: "apple juice", category: "beverage", fridgeDays: 10, freezerDays: 240, perishable: true, keywords: ["apple juice"] },
  { name: "soda", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["soda", "pop", "coke", "pepsi", "sprite"] },
  { name: "beer", category: "beverage", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["beer"] },
  { name: "wine", category: "beverage", fridgeDays: 5, freezerDays: null, perishable: true, keywords: ["wine", "red wine", "white wine"] },
  { name: "vodka", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["vodka", "liquor"] },
  { name: "whiskey", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["whiskey", "whisky", "bourbon", "scotch"] },
  { name: "gin", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["gin"] },
  { name: "rum", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["rum"] },
  { name: "tequila", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["tequila"] },
  { name: "almond milk", category: "beverage", fridgeDays: 10, freezerDays: null, perishable: true, keywords: ["almond milk"] },
  { name: "soy milk", category: "beverage", fridgeDays: 10, freezerDays: null, perishable: true, keywords: ["soy milk", "soymilk"] },
  { name: "oat milk", category: "beverage", fridgeDays: 10, freezerDays: null, perishable: true, keywords: ["oat milk"] },
  { name: "kombucha", category: "beverage", fridgeDays: 30, freezerDays: null, perishable: true, keywords: ["kombucha"] },
  { name: "energy drink", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["energy drink", "red bull", "monster"] },
  { name: "coconut water", category: "beverage", fridgeDays: 3, freezerDays: 30, perishable: true, keywords: ["coconut water"] },
  { name: "iced tea", category: "beverage", fridgeDays: 5, freezerDays: null, perishable: true, keywords: ["iced tea"] },
  { name: "lemonade", category: "beverage", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["lemonade"] },
  { name: "grape juice", category: "beverage", fridgeDays: 10, freezerDays: 240, perishable: true, keywords: ["grape juice"] },
  { name: "cranberry juice", category: "beverage", fridgeDays: 21, freezerDays: 240, perishable: true, keywords: ["cranberry juice"] },
  { name: "pineapple juice", category: "beverage", fridgeDays: 7, freezerDays: 240, perishable: true, keywords: ["pineapple juice"] },
  { name: "tomato juice", category: "beverage", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["tomato juice"] },
  { name: "sports drink", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["sports drink", "gatorade", "powerade"] },
  { name: "seltzer", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["seltzer", "sparkling water", "club soda", "la croix"] },
  { name: "tonic water", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["tonic water"] },
  { name: "cold brew coffee", category: "beverage", fridgeDays: 10, freezerDays: null, perishable: true, keywords: ["cold brew", "cold brew coffee"] },
  { name: "hot chocolate mix", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["hot chocolate mix", "hot cocoa mix"] },
  { name: "drink mix powder", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["drink mix", "kool-aid", "crystal light"] },
  { name: "champagne", category: "beverage", fridgeDays: 3, freezerDays: null, perishable: true, keywords: ["champagne", "sparkling wine", "prosecco", "cava"] },
  { name: "sake", category: "beverage", fridgeDays: 14, freezerDays: null, perishable: true, keywords: ["sake"] },
  { name: "hard cider", category: "beverage", fridgeDays: 7, freezerDays: null, perishable: true, keywords: ["hard cider", "cider"] },
  { name: "hard seltzer", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["hard seltzer", "white claw", "truly"] },
  { name: "egg nog", category: "beverage", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["egg nog", "eggnog"] },

  // Snacks
  { name: "potato chips", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["potato chips", "chips", "crisps", "lays"] },
  { name: "tortilla chips", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["tortilla chips", "doritos", "tostitos"] },
  { name: "pretzels", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["pretzels"] },
  { name: "popcorn", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["popcorn", "microwaved popcorn"] },
  { name: "nuts", category: "snack", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["nuts", "mixed nuts"] },
  { name: "trail mix", category: "snack", fridgeDays: null, freezerDays: 180, perishable: false, keywords: ["trail mix"] },
  { name: "granola bars", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["granola bar", "granola bars"] },
  { name: "fruit snacks", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["fruit snacks"] },
  { name: "chocolate bar", category: "snack", fridgeDays: null, freezerDays: 365, perishable: false, keywords: ["chocolate", "chocolate bar", "hersheys", "cadbury"] },
  { name: "candy", category: "snack", fridgeDays: null, freezerDays: 365, perishable: false, keywords: ["candy", "sweets"] },
  { name: "beef jerky", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["beef jerky"] },
  { name: "rice cakes", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["rice cakes"] },
  { name: "seaweed snacks", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["seaweed snacks"] },
  { name: "protein bar", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["protein bar", "protein bars"] },
  { name: "pocky", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["pocky"] },
  { name: "graham crackers", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["graham crackers"] },
  { name: "animal crackers", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["animal crackers"] },
  { name: "goldfish crackers", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["goldfish", "goldfish crackers"] },
  { name: "cheez-its", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cheez-it", "cheez-its"] },
  { name: "fruit leather", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["fruit leather", "fruit roll-up"] },
  { name: "almond butter", category: "snack", fridgeDays: 90, freezerDays: null, perishable: false, keywords: ["almond butter"] },
  { name: "cashew butter", category: "snack", fridgeDays: 90, freezerDays: null, perishable: false, keywords: ["cashew butter"] },
  { name: "nutella", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["nutella", "chocolate hazelnut spread"] },
  { name: "sunflower seeds", category: "snack", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["sunflower seeds"] },
  { name: "pumpkin seeds", category: "snack", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["pumpkin seeds", "pepitas"] },
  { name: "chia seeds", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["chia seeds"] },
  { name: "flax seeds", category: "snack", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["flax seeds", "linseed"] },
  { name: "dried apricots", category: "snack", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["dried apricots"] },
  { name: "raisins", category: "snack", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["raisins", "sultanas"] },
  { name: "prunes", category: "snack", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["prunes", "dried plums"] },
  { name: "dried figs", category: "snack", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["dried figs"] },
  { name: "dried dates", category: "snack", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["dried dates"] },
  { name: "dried mango", category: "snack", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["dried mango"] },
  { name: "dried cranberries", category: "snack", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["dried cranberries", "craisins"] },
  { name: "banana chips", category: "snack", fridgeDays: null, freezerDays: 90, perishable: false, keywords: ["banana chips"] },
  { name: "apple chips", category: "snack", fridgeDays: null, freezerDays: 90, perishable: false, keywords: ["apple chips"] },
  { name: "veggie straws", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["veggie straws"] },

  // Herbs
  { name: "basil", category: "herb", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["basil"] },
  { name: "parsley", category: "herb", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["parsley"] },
  { name: "cilantro", category: "herb", fridgeDays: 10, freezerDays: 180, perishable: true, keywords: ["cilantro", "coriander"] },
  { name: "rosemary", category: "herb", fridgeDays: 21, freezerDays: 180, perishable: true, keywords: ["rosemary"] },
  { name: "thyme", category: "herb", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["thyme"] },
  { name: "oregano", category: "herb", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["oregano"] },
  { name: "mint", category: "herb", fridgeDays: 10, freezerDays: 180, perishable: true, keywords: ["mint"] },
  { name: "dill", category: "herb", fridgeDays: 10, freezerDays: 180, perishable: true, keywords: ["dill"] },
  { name: "sage", category: "herb", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["sage"] },
  { name: "chives", category: "herb", fridgeDays: 10, freezerDays: 180, perishable: true, keywords: ["chives"] },
  { name: "lemongrass", category: "herb", fridgeDays: 21, freezerDays: 180, perishable: true, keywords: ["lemongrass"] },
  { name: "marjoram", category: "herb", fridgeDays: 10, freezerDays: 180, perishable: true, keywords: ["marjoram"] },
  { name: "tarragon", category: "herb", fridgeDays: 10, freezerDays: 180, perishable: true, keywords: ["tarragon"] },
  { name: "lavender", category: "herb", fridgeDays: 10, freezerDays: 180, perishable: true, keywords: ["lavender"] },
  { name: "bay leaf", category: "herb", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["bay leaf", "bay leaves"] },

  // Grains
  { name: "quinoa", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["quinoa"] },
  { name: "barley", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["barley"] },
  { name: "couscous", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["couscous"] },
  { name: "farro", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["farro"] },
  { name: "bulgur", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["bulgur", "bulgur wheat"] },
  { name: "millet", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["millet"] },
  { name: "polenta", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["polenta"] },
  { name: "grits", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["grits"] },
  { name: "buckwheat", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["buckwheat", "kasha"] },
  { name: "sorghum", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["sorghum"] },
  { name: "amaranth", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["amaranth"] },
  { name: "teff", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["teff"] },
  { name: "spelt", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["spelt"] },
  { name: "freekeh", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["freekeh"] },
  { name: "wheat berries", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["wheat berries"] },

  // Nuts
  { name: "almonds", category: "nut", fridgeDays: 365, freezerDays: 730, perishable: false, keywords: ["almond", "almonds"] },
  { name: "walnuts", category: "nut", fridgeDays: 365, freezerDays: 730, perishable: false, keywords: ["walnut", "walnuts"] },
  { name: "pecans", category: "nut", fridgeDays: 270, freezerDays: 730, perishable: false, keywords: ["pecan", "pecans"] },
  { name: "cashews", category: "nut", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["cashew", "cashews"] },
  { name: "pistachios", category: "nut", fridgeDays: 270, freezerDays: 365, perishable: false, keywords: ["pistachio", "pistachios"] },
  { name: "peanuts", category: "nut", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["peanut", "peanuts"] },
  { name: "macadamia nuts", category: "nut", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["macadamia", "macadamia nuts"] },
  { name: "hazelnuts", category: "nut", fridgeDays: 270, freezerDays: 365, perishable: false, keywords: ["hazelnut", "hazelnuts"] },
  { name: "pine nuts", category: "nut", fridgeDays: 90, freezerDays: 180, perishable: false, keywords: ["pine nut", "pine nuts", "pignoli"] },
  { name: "brazil nuts", category: "nut", fridgeDays: 270, freezerDays: 365, perishable: false, keywords: ["brazil nut", "brazil nuts"] },
  { name: "chestnuts", category: "nut", fridgeDays: 21, freezerDays: 270, perishable: true, keywords: ["chestnut", "chestnuts"] },
  
  // Oils
  { name: "olive oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["olive oil", "extra virgin olive oil"] },
  { name: "vegetable oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["vegetable oil"] },
  { name: "canola oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["canola oil"] },
  { name: "coconut oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["coconut oil"] },
  { name: "sesame oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["sesame oil"] },
  { name: "avocado oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["avocado oil"] },
  { name: "sunflower oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["sunflower oil"] },
  { name: "peanut oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["peanut oil"] },
  { name: "corn oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["corn oil"] },
  { name: "grapeseed oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["grapeseed oil"] },
  { name: "flaxseed oil", category: "oil", fridgeDays: 90, freezerDays: 180, perishable: true, keywords: ["flaxseed oil"] },
  { name: "walnut oil", category: "oil", fridgeDays: 180, freezerDays: 365, perishable: true, keywords: ["walnut oil"] },
  { name: "truffle oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["truffle oil"] },
  { name: "palm oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["palm oil"] },
  { name: "shortening", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["shortening", "crisco"] },
  { name: "lard", category: "oil", fridgeDays: 365, freezerDays: null, perishable: false, keywords: ["lard"] },

  // Sauces
  { name: "tomato sauce", category: "sauce", fridgeDays: 7, freezerDays: 180, perishable: false, keywords: ["tomato sauce", "pasta sauce", "passata"] },
  { name: "marinara sauce", category: "sauce", fridgeDays: 7, freezerDays: 180, perishable: false, keywords: ["marinara sauce"] },
  { name: "alfredo sauce", category: "sauce", fridgeDays: 5, freezerDays: null, perishable: true, keywords: ["alfredo", "alfredo sauce"] },
  { name: "pesto", category: "sauce", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["pesto", "pesto sauce"] },
  { name: "salsa", category: "sauce", fridgeDays: 14, freezerDays: 60, perishable: true, keywords: ["salsa"] },
  { name: "guacamole", category: "sauce", fridgeDays: 3, freezerDays: 90, perishable: true, keywords: ["guacamole", "guac"] },
  { name: "hummus", category: "sauce", fridgeDays: 7, freezerDays: 120, perishable: true, keywords: ["hummus", "houmous"] },
  { name: "tzatziki", category: "sauce", fridgeDays: 7, freezerDays: null, perishable: true, keywords: ["tzatziki"] },
  { name: "teriyaki sauce", category: "sauce", fridgeDays: 90, freezerDays: null, perishable: false, keywords: ["teriyaki sauce"] },
  { name: "cranberry sauce", category: "sauce", fridgeDays: 14, freezerDays: 60, perishable: false, keywords: ["cranberry sauce"] },
  { name: "apple butter", category: "sauce", fridgeDays: 30, freezerDays: 365, perishable: false, keywords: ["apple butter"] },
  { name: "chutney", category: "sauce", fridgeDays: 30, freezerDays: null, perishable: false, keywords: ["chutney", "mango chutney"] },
  { name: "curry paste", category: "sauce", fridgeDays: 30, freezerDays: 180, perishable: true, keywords: ["curry paste", "red curry paste", "green curry paste"] },
  { name: "tomato paste", category: "sauce", fridgeDays: 10, freezerDays: 90, perishable: true, keywords: ["tomato paste"] },
  { name: "enchilada sauce", category: "sauce", fridgeDays: 7, freezerDays: 180, perishable: false, keywords: ["enchilada sauce"] },
  { name: "mole sauce", category: "sauce", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["mole sauce"] },

  // Spices
  { name: "black pepper", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["black pepper", "peppercorns"] },
  { name: "cinnamon", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cinnamon", "cinnamon sticks"] },
  { name: "cumin", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cumin"] },
  { name: "paprika", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["paprika", "smoked paprika"] },
  { name: "chili powder", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["chili powder"] },
  { name: "garlic powder", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["garlic powder"] },
  { name: "onion powder", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["onion powder"] },
  { name: "turmeric", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["turmeric"] },
  { name: "ginger powder", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["ginger powder", "ground ginger"] },
  { name: "nutmeg", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["nutmeg"] },
  { name: "cloves", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cloves", "ground cloves"] },
  { name: "cayenne pepper", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cayenne pepper"] },
  { name: "red pepper flakes", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["red pepper flakes", "crushed red pepper"] },
  { name: "curry powder", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["curry powder"] },
  { name: "dried oregano", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["dried oregano"] },
  { name: "dried basil", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["dried basil"] },
  { name: "dried thyme", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["dried thyme"] },
  { name: "dried rosemary", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["dried rosemary"] },
  { name: "allspice", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["allspice"] },
  { name: "cardamom", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cardamom"] },
  { name: "coriander seed", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["coriander seed", "ground coriander"] },
  { name: "mustard seed", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["mustard seed", "mustard powder"] },
  { name: "star anise", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["star anise"] },
  { name: "vanilla bean", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["vanilla bean"] },
  { name: "poppy seeds", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["poppy seeds"] },
  { name: "sesame seeds", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["sesame seeds"] },
  { name: "fennel seed", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["fennel seed"] },
  { name: "celery seed", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["celery seed"] },
  { name: "dill seed", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["dill seed"] },
  { name: "caraway seed", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["caraway seed"] },
  { name: "anise seed", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["anise seed"] },
  { name: "juniper berries", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["juniper berries"] },
  { name: "saffron", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["saffron"] },
  { name: "garam masala", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["garam masala"] },
  { name: "chinese five spice", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["chinese five spice", "five-spice powder"] },
  { name: "za'atar", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["za'atar", "zaatar"] },
  { name: "sumac", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["sumac"] },
  { name: "herbes de provence", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["herbes de provence"] },
  { name: "cajun seasoning", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cajun seasoning"] },
  { name: "old bay seasoning", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["old bay", "old bay seasoning"] },
  { name: "taco seasoning", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["taco seasoning"] },
  { name: "pumpkin pie spice", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["pumpkin pie spice"] },
  { name: "apple pie spice", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["apple pie spice"] },

  // Spreads
  { name: "butter spread", category: "spread", fridgeDays: 90, freezerDays: 270, perishable: true, keywords: ["butter spread", "margarine"] },
  { name: "fruit spread", category: "spread", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["fruit spread", "jam", "jelly"] },
  { name: "lemon curd", category: "spread", fridgeDays: 14, freezerDays: 365, perishable: true, keywords: ["lemon curd"] },
  { name: "honey butter", category: "spread", fridgeDays: 90, freezerDays: 270, perishable: true, keywords: ["honey butter"] },
  { name: "pimento cheese", category: "spread", fridgeDays: 14, freezerDays: null, perishable: true, keywords: ["pimento cheese"] },
  { name: "tapenade", category: "spread", fridgeDays: 14, freezerDays: 60, perishable: true, keywords: ["tapenade", "olive tapenade"] },
  { name: "boursin", category: "spread", fridgeDays: 14, freezerDays: null, perishable: true, keywords: ["boursin", "garlic and herb spread"] },
  { name: "deviled ham spread", category: "spread", fridgeDays: 5, freezerDays: null, perishable: true, keywords: ["deviled ham"] },

  // Plant-Based
  { name: "tofu", category: "plant-based", fridgeDays: 5, freezerDays: 150, perishable: true, keywords: ["tofu", "bean curd"] },
  { name: "tempeh", category: "plant-based", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["tempeh"] },
  { name: "seitan", category: "plant-based", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["seitan", "wheat meat"] },
  { name: "veggie burger", category: "plant-based", fridgeDays: 3, freezerDays: 180, perishable: true, keywords: ["veggie burger", "plant-based burger"] },
  { name: "vegan sausage", category: "plant-based", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["vegan sausage", "beyond sausage", "impossible sausage"] },
  { name: "vegan ground meat", category: "plant-based", fridgeDays: 3, freezerDays: 180, perishable: true, keywords: ["vegan ground", "beyond meat", "impossible foods"] },
  { name: "vegan cheese", category: "plant-based", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["vegan cheese", "daiya", "violife"] },
  { name: "vegan yogurt", category: "plant-based", fridgeDays: 10, freezerDays: 60, perishable: true, keywords: ["vegan yogurt", "soy yogurt", "coconut yogurt"] },
  { name: "vegan butter", category: "plant-based", fridgeDays: 90, freezerDays: 270, perishable: true, keywords: ["vegan butter", "margarine"] },
  { name: "vegan cream cheese", category: "plant-based", fridgeDays: 14, freezerDays: 120, perishable: true, keywords: ["vegan cream cheese"] },
  { name: "vegan sour cream", category: "plant-based", fridgeDays: 14, freezerDays: null, perishable: true, keywords: ["vegan sour cream"] },
  { name: "vegan mayonnaise", category: "plant-based", fridgeDays: 60, freezerDays: null, perishable: true, keywords: ["vegan mayo", "veganaise"] },
  { name: "jackfruit", category: "plant-based", fridgeDays: 5, freezerDays: 60, perishable: true, keywords: ["jackfruit"] },
  { name: "lentil soup", category: "plant-based", fridgeDays: 4, freezerDays: 180, perishable: true, keywords: ["lentil soup"] },
  { name: "cashew milk", category: "plant-based", fridgeDays: 10, freezerDays: null, perishable: true, keywords: ["cashew milk"] },
  { name: "rice milk", category: "plant-based", fridgeDays: 10, freezerDays: null, perishable: true, keywords: ["rice milk"] },
  { name: "hemp milk", category: "plant-based", fridgeDays: 10, freezerDays: null, perishable: true, keywords: ["hemp milk"] },
  { name: "flax milk", category: "plant-based", fridgeDays: 10, freezerDays: null, perishable: true, keywords: ["flax milk"] },
  { name: "vegan ice cream", category: "plant-based", fridgeDays: null, freezerDays: 90, perishable: true, keywords: ["vegan ice cream", "non-dairy ice cream"] },
  { name: "kimchi", category: "plant-based", fridgeDays: 180, freezerDays: null, perishable: true, keywords: ["kimchi", "kim chee"] },
  { name: "sauerkraut", category: "plant-based", fridgeDays: 180, freezerDays: null, perishable: true, keywords: ["sauerkraut"] },

  // Baby Food
  { name: "baby food puree", category: "baby", fridgeDays: 2, freezerDays: 90, perishable: true, keywords: ["baby food", "baby food puree", "jarred baby food"] },
  { name: "baby formula (prepared)", category: "baby", fridgeDays: 1, freezerDays: null, perishable: true, keywords: ["baby formula", "formula", "infant formula"] },
  { name: "baby formula (powder)", category: "baby", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["baby formula powder", "powdered formula"] },
  { name: "baby cereal", category: "baby", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["baby cereal", "rice cereal", "oatmeal cereal"] },
  { name: "puffs", category: "baby", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["baby puffs", "gerber puffs"] },
  { name: "yogurt melts", category: "baby", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["yogurt melts"] },
  { name: "teething biscuits", category: "baby", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["teething biscuits", "teething crackers", "rusks"] },
  { name: "breast milk", category: "baby", fridgeDays: 4, freezerDays: 180, perishable: true, keywords: ["breast milk", "expressed milk"] },
  { name: "baby food pouch", category: "baby", fridgeDays: 1, freezerDays: null, perishable: true, keywords: ["baby food pouch", "squeeze pouch"] },

  // Pet Food
  { name: "dry dog food", category: "pet", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["dog food", "kibble", "dry dog food"] },
  { name: "dry cat food", category: "pet", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cat food", "cat kibble", "dry cat food"] },
  { name: "wet dog food (opened)", category: "pet", fridgeDays: 3, freezerDays: 60, perishable: true, keywords: ["wet dog food", "canned dog food"] },
  { name: "wet cat food (opened)", category: "pet", fridgeDays: 3, freezerDays: 60, perishable: true, keywords: ["wet cat food", "canned cat food"] },
  { name: "dog treats", category: "pet", fridgeDays: null, freezerDays: 180, perishable: false, keywords: ["dog treats", "dog biscuits"] },
  { name: "cat treats", category: "pet", fridgeDays: null, freezerDays: 180, perishable: false, keywords: ["cat treats"] },
  { name: "raw pet food", category: "pet", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["raw dog food", "raw cat food"] },
  { name: "bird seed", category: "pet", fridgeDays: null, freezerDays: 365, perishable: false, keywords: ["bird seed"] },
  { name: "fish food", category: "pet", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["fish food", "fish flakes"] },
  { name: "rabbit food", category: "pet", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["rabbit food", "rabbit pellets"] },
  { name: "hamster food", category: "pet", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["hamster food"] },

  // Leftovers
  { name: "leftovers", category: "leftovers", fridgeDays: 4, freezerDays: 90, perishable: true, keywords: ["leftovers", "leftover"] },
  { name: "cooked rice", category: "leftovers", fridgeDays: 4, freezerDays: 180, perishable: true, keywords: ["cooked rice"] },
  { name: "cooked pasta", category: "leftovers", fridgeDays: 4, freezerDays: 60, perishable: true, keywords: ["cooked pasta"] },
  { name: "cooked chicken", category: "leftovers", fridgeDays: 4, freezerDays: 120, perishable: true, keywords: ["cooked chicken"] },
  { name: "cooked beef", category: "leftovers", fridgeDays: 4, freezerDays: 90, perishable: true, keywords: ["cooked beef"] },
  { name: "cooked pork", category: "leftovers", fridgeDays: 4, freezerDays: 90, perishable: true, keywords: ["cooked pork"] },
  { name: "cooked fish", category: "leftovers", fridgeDays: 3, freezerDays: 90, perishable: true, keywords: ["cooked fish"] },
  { name: "soup leftovers", category: "leftovers", fridgeDays: 4, freezerDays: 120, perishable: true, keywords: ["soup leftovers", "leftover soup"] },
  { name: "casserole leftovers", category: "leftovers", fridgeDays: 4, freezerDays: 90, perishable: true, keywords: ["casserole leftovers", "leftover casserole"] },
  { name: "pizza leftovers", category: "leftovers", fridgeDays: 4, freezerDays: 60, perishable: true, keywords: ["pizza leftovers", "leftover pizza"] },
  { name: "takeout", category: "leftovers", fridgeDays: 4, freezerDays: 90, perishable: true, keywords: ["takeout", "takeaway", "chinese takeout"] }
];
