export interface ProduceItem {
  name: string;
  category: string;
  fridgeDays: number | null;
  freezerDays: number | null;
  perishable: boolean;
  keywords: string[];
}

export const PRODUCE_KNOWLEDGE: ProduceItem[] = [
  // Fruits
  { name: "apple", category: "fruit", fridgeDays: 42, freezerDays: 240, perishable: true, keywords: ["apple", "apples", "gala", "fuji", "granny smith", "honeycrisp"] },
  { name: "avocado", category: "fruit", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["avocado", "avos"] },
  { name: "banana", category: "fruit", fridgeDays: 5, freezerDays: 90, perishable: true, keywords: ["banana", "bananas"] },
  { name: "blueberry", category: "fruit", fridgeDays: 10, freezerDays: 300, perishable: true, keywords: ["blueberry", "blueberries"] },
  { name: "raspberry", category: "fruit", fridgeDays: 3, freezerDays: 180, perishable: true, keywords: ["raspberry", "raspberries"] },
  { name: "strawberry", category: "fruit", fridgeDays: 5, freezerDays: 180, perishable: true, keywords: ["strawberry", "strawberries"] },
  { name: "blackberry", category: "fruit", fridgeDays: 4, freezerDays: 240, perishable: true, keywords: ["blackberry", "blackberries"] },
  { name: "grape", category: "fruit", fridgeDays: 14, freezerDays: 300, perishable: true, keywords: ["grape", "grapes"] },
  { name: "watermelon", category: "fruit", fridgeDays: 14, freezerDays: null, perishable: true, keywords: ["watermelon"] },
  { name: "cantaloupe", category: "fruit", fridgeDays: 7, freezerDays: 300, perishable: true, keywords: ["cantaloupe", "rockmelon"] },
  { name: "honeydew", category: "fruit", fridgeDays: 10, freezerDays: 300, perishable: true, keywords: ["honeydew", "honeydew melon"] },
  { name: "pineapple", category: "fruit", fridgeDays: 5, freezerDays: 180, perishable: true, keywords: ["pineapple"] },
  { name: "mango", category: "fruit", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["mango", "mangoes"] },
  { name: "peach", category: "fruit", fridgeDays: 5, freezerDays: 240, perishable: true, keywords: ["peach", "peaches"] },
  { name: "nectarine", category: "fruit", fridgeDays: 5, freezerDays: 240, perishable: true, keywords: ["nectarine", "nectarines"] },
  { name: "plum", category: "fruit", fridgeDays: 5, freezerDays: 240, perishable: true, keywords: ["plum", "plums"] },
  { name: "cherry", category: "fruit", fridgeDays: 7, freezerDays: 300, perishable: true, keywords: ["cherry", "cherries"] },
  { name: "lemon", category: "fruit", fridgeDays: 28, freezerDays: 90, perishable: true, keywords: ["lemon", "lemons"] },
  { name: "lime", category: "fruit", fridgeDays: 28, freezerDays: 90, perishable: true, keywords: ["lime", "limes"] },
  { name: "grapefruit", category: "fruit", fridgeDays: 21, freezerDays: 30, perishable: true, keywords: ["grapefruit"] },
  { name: "kiwi", category: "fruit", fridgeDays: 14, freezerDays: 240, perishable: true, keywords: ["kiwi", "kiwifruit"] },
  { name: "pear", category: "fruit", fridgeDays: 7, freezerDays: 240, perishable: true, keywords: ["pear", "pears"] },
  { name: "fig", category: "fruit", fridgeDays: 3, freezerDays: 180, perishable: true, keywords: ["fig", "figs"] },
  { name: "pomegranate", category: "fruit", fridgeDays: 30, freezerDays: 365, perishable: true, keywords: ["pomegranate"] },
  { name: "coconut", category: "fruit", fridgeDays: 7, freezerDays: 240, perishable: true, keywords: ["coconut"] },
  { name: "orange", category: "fruit", fridgeDays: 21, freezerDays: 90, perishable: true, keywords: ["orange", "oranges"] },
  { name: "apricot", category: "fruit", fridgeDays: 4, freezerDays: 180, perishable: true, keywords: ["apricot", "apricots"] },
  { name: "cranberry", category: "fruit", fridgeDays: 30, freezerDays: 365, perishable: true, keywords: ["cranberry", "cranberries"] },
  { name: "date", category: "fruit", fridgeDays: 180, freezerDays: 365, perishable: true, keywords: ["date", "dates"] },
  { name: "guava", category: "fruit", fridgeDays: 4, freezerDays: 240, perishable: true, keywords: ["guava"] },
  { name: "passion fruit", category: "fruit", fridgeDays: 14, freezerDays: 300, perishable: true, keywords: ["passion fruit", "passionfruit"] },
  { name: "papaya", category: "fruit", fridgeDays: 3, freezerDays: 240, perishable: true, keywords: ["papaya"] },
  { name: "lychee", category: "fruit", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["lychee", "litchi"] },
  { name: "persimmon", category: "fruit", fridgeDays: 5, freezerDays: 240, perishable: true, keywords: ["persimmon"] },
  { name: "tangerine", category: "fruit", fridgeDays: 14, freezerDays: 90, perishable: true, keywords: ["tangerine", "mandarin"] },

  // Vegetables
  { name: "carrot", category: "vegetable", fridgeDays: 28, freezerDays: 365, perishable: true, keywords: ["carrot", "carrots"] },
  { name: "broccoli", category: "vegetable", fridgeDays: 7, freezerDays: 365, perishable: true, keywords: ["broccoli", "brocolli"] },
  { name: "spinach", category: "vegetable", fridgeDays: 7, freezerDays: 300, perishable: true, keywords: ["spinach"] },
  { name: "lettuce", category: "vegetable", fridgeDays: 10, freezerDays: null, perishable: true, keywords: ["lettuce", "romaine", "iceberg"] },
  { name: "cucumber", category: "vegetable", fridgeDays: 14, freezerDays: null, perishable: true, keywords: ["cucumber", "cucumbers"] },
  { name: "bell pepper", category: "vegetable", fridgeDays: 14, freezerDays: 240, perishable: true, keywords: ["bell pepper", "capsicum", "pepper", "peppers"] },
  { name: "onion", category: "vegetable", fridgeDays: 60, freezerDays: 240, perishable: false, keywords: ["onion", "onions"] },
  { name: "garlic", category: "vegetable", fridgeDays: 90, freezerDays: 300, perishable: false, keywords: ["garlic"] },
  { name: "potato", category: "vegetable", fridgeDays: null, freezerDays: 300, perishable: false, keywords: ["potato", "potatoes"] },
  { name: "sweet potato", category: "vegetable", fridgeDays: null, freezerDays: 300, perishable: false, keywords: ["sweet potato", "yam"] },
  { name: "tomato", category: "vegetable", fridgeDays: 7, freezerDays: 240, perishable: true, keywords: ["tomato", "tomatoes"] },
  { name: "celery", category: "vegetable", fridgeDays: 28, freezerDays: 300, perishable: true, keywords: ["celery"] },
  { name: "mushroom", category: "vegetable", fridgeDays: 7, freezerDays: 300, perishable: true, keywords: ["mushroom", "mushrooms"] },
  { name: "corn", category: "vegetable", fridgeDays: 3, freezerDays: 365, perishable: true, keywords: ["corn", "corn on the cob"] },
  { name: "green beans", category: "vegetable", fridgeDays: 7, freezerDays: 365, perishable: true, keywords: ["green beans", "string beans"] },
  { name: "peas", category: "vegetable", fridgeDays: 5, freezerDays: 365, perishable: true, keywords: ["peas", "green peas"] },
  { name: "cauliflower", category: "vegetable", fridgeDays: 7, freezerDays: 300, perishable: true, keywords: ["cauliflower"] },
  { name: "asparagus", category: "vegetable", fridgeDays: 4, freezerDays: 300, perishable: true, keywords: ["asparagus"] },
  { name: "eggplant", category: "vegetable", fridgeDays: 7, freezerDays: 240, perishable: true, keywords: ["eggplant", "aubergine"] },
  { name: "zucchini", category: "vegetable", fridgeDays: 5, freezerDays: 300, perishable: true, keywords: ["zucchini", "courgette"] },
  { name: "cabbage", category: "vegetable", fridgeDays: 28, freezerDays: null, perishable: true, keywords: ["cabbage"] },
  { name: "kale", category: "vegetable", fridgeDays: 7, freezerDays: 240, perishable: true, keywords: ["kale"] },
  { name: "radish", category: "vegetable", fridgeDays: 14, freezerDays: null, perishable: true, keywords: ["radish", "radishes"] },
  { name: "beet", category: "vegetable", fridgeDays: 14, freezerDays: 240, perishable: true, keywords: ["beet", "beetroot", "beets"] },
  { name: "brussels sprout", category: "vegetable", fridgeDays: 10, freezerDays: 365, perishable: true, keywords: ["brussels sprout", "brussel sprout", "brussels sprouts"] },
  { name: "scallion", category: "vegetable", fridgeDays: 10, freezerDays: 60, perishable: true, keywords: ["scallion", "green onion", "spring onion"] },
  { name: "leek", category: "vegetable", fridgeDays: 14, freezerDays: 90, perishable: true, keywords: ["leek", "leeks"] },
  { name: "artichoke", category: "vegetable", fridgeDays: 7, freezerDays: 240, perishable: true, keywords: ["artichoke", "artichokes"] },
  { name: "pumpkin", category: "vegetable", fridgeDays: 90, freezerDays: 300, perishable: false, keywords: ["pumpkin"] },
  { name: "squash", category: "vegetable", fridgeDays: 14, freezerDays: 300, perishable: true, keywords: ["squash", "butternut squash", "spaghetti squash", "acorn squash"] },
  { name: "bok choy", category: "vegetable", fridgeDays: 7, freezerDays: null, perishable: true, keywords: ["bok choy", "pak choi"] },
  { name: "chard", category: "vegetable", fridgeDays: 5, freezerDays: 300, perishable: true, keywords: ["chard", "swiss chard"] },
  { name: "collard greens", category: "vegetable", fridgeDays: 5, freezerDays: 300, perishable: true, keywords: ["collard greens", "collards"] },
  { name: "fennel", category: "vegetable", fridgeDays: 10, freezerDays: 240, perishable: true, keywords: ["fennel"] },
  { name: "jicama", category: "vegetable", fridgeDays: 21, freezerDays: null, perishable: false, keywords: ["jicama"] },
  { name: "kohlrabi", category: "vegetable", fridgeDays: 21, freezerDays: 300, perishable: true, keywords: ["kohlrabi"] },
  { name: "okra", category: "vegetable", fridgeDays: 4, freezerDays: 270, perishable: true, keywords: ["okra"] },
  { name: "parsnip", category: "vegetable", fridgeDays: 28, freezerDays: 270, perishable: true, keywords: ["parsnip", "parsnips"] },
  { name: "rutabaga", category: "vegetable", fridgeDays: 30, freezerDays: 270, perishable: false, keywords: ["rutabaga"] },
  { name: "snow peas", category: "vegetable", fridgeDays: 7, freezerDays: 365, perishable: true, keywords: ["snow peas"] },
  { name: "sugar snap peas", category: "vegetable", fridgeDays: 7, freezerDays: 365, perishable: true, keywords: ["sugar snap peas", "snap peas"] },
  { name: "turnip", category: "vegetable", fridgeDays: 14, freezerDays: 270, perishable: true, keywords: ["turnip", "turnips"] },
  { name: "watercress", category: "vegetable", fridgeDays: 4, freezerDays: null, perishable: true, keywords: ["watercress"] },
  { name: "arugula", category: "vegetable", fridgeDays: 7, freezerDays: null, perishable: true, keywords: ["arugula", "rocket"] },
  { name: "endive", category: "vegetable", fridgeDays: 7, freezerDays: null, perishable: true, keywords: ["endive", "belgian endive"] },

  // Dairy
  { name: "milk", category: "dairy", fridgeDays: 7, freezerDays: 90, perishable: true, keywords: ["milk"] },
  { name: "cheddar cheese", category: "dairy", fridgeDays: 28, freezerDays: 180, perishable: true, keywords: ["cheddar", "cheddar cheese"] },
  { name: "mozzarella cheese", category: "dairy", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["mozzarella", "mozzarella cheese"] },
  { name: "parmesan cheese", category: "dairy", fridgeDays: 180, freezerDays: 180, perishable: true, keywords: ["parmesan", "parmesan cheese"] },
  { name: "feta cheese", category: "dairy", fridgeDays: 30, freezerDays: 180, perishable: true, keywords: ["feta", "feta cheese"] },
  { name: "goat cheese", category: "dairy", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["goat cheese", "chèvre"] },
  { name: "blue cheese", category: "dairy", fridgeDays: 21, freezerDays: 180, perishable: true, keywords: ["blue cheese", "bleu cheese"] },
  { name: "butter", category: "dairy", fridgeDays: 90, freezerDays: 270, perishable: true, keywords: ["butter"] },
  { name: "yogurt", category: "dairy", fridgeDays: 14, freezerDays: 60, perishable: true, keywords: ["yogurt", "yoghurt"] },
  { name: "cream cheese", category: "dairy", fridgeDays: 14, freezerDays: 120, perishable: true, keywords: ["cream cheese"] },
  { name: "sour cream", category: "dairy", fridgeDays: 21, freezerDays: null, perishable: true, keywords: ["sour cream"] },
  { name: "cottage cheese", category: "dairy", fridgeDays: 10, freezerDays: 60, perishable: true, keywords: ["cottage cheese"] },
  { name: "heavy cream", category: "dairy", fridgeDays: 7, freezerDays: 120, perishable: true, keywords: ["heavy cream", "whipping cream"] },
  { name: "half-and-half", category: "dairy", fridgeDays: 7, freezerDays: 120, perishable: true, keywords: ["half-and-half", "half & half"] },
  { name: "eggs", category: "dairy", fridgeDays: 28, freezerDays: 365, perishable: true, keywords: ["egg", "eggs"] },

  // Meat
  { name: "ground beef", category: "meat", fridgeDays: 2, freezerDays: 120, perishable: true, keywords: ["ground beef", "mince", "beef mince"] },
  { name: "steak", category: "meat", fridgeDays: 4, freezerDays: 270, perishable: true, keywords: ["steak", "beef steak"] },
  { name: "beef roast", category: "meat", fridgeDays: 4, freezerDays: 270, perishable: true, keywords: ["beef roast"] },
  { name: "pork chop", category: "meat", fridgeDays: 4, freezerDays: 180, perishable: true, keywords: ["pork chop", "pork chops"] },
  { name: "pork roast", category: "meat", fridgeDays: 4, freezerDays: 180, perishable: true, keywords: ["pork roast"] },
  { name: "bacon", category: "meat", fridgeDays: 7, freezerDays: 120, perishable: true, keywords: ["bacon"] },
  { name: "sausage", category: "meat", fridgeDays: 2, freezerDays: 60, perishable: true, keywords: ["sausage", "sausages"] },
  { name: "ham", category: "meat", fridgeDays: 5, freezerDays: 60, perishable: true, keywords: ["ham", "deli ham"] },
  { name: "lamb", category: "meat", fridgeDays: 4, freezerDays: 270, perishable: true, keywords: ["lamb", "lamb chops"] },
  { name: "veal", category: "meat", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["veal"] },
  { name: "hot dog", category: "meat", fridgeDays: 7, freezerDays: 60, perishable: true, keywords: ["hot dog", "hot dogs", "frankfurter", "weiner"] },
  { name: "pepperoni", category: "meat", fridgeDays: 21, freezerDays: 180, perishable: true, keywords: ["pepperoni"] },

  // Seafood
  { name: "salmon", category: "seafood", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["salmon"] },
  { name: "tuna", category: "seafood", fridgeDays: 2, freezerDays: 90, perishable: true, keywords: ["tuna", "tuna steak"] },
  { name: "shrimp", category: "seafood", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["shrimp", "prawns"] },
  { name: "cod", category: "seafood", fridgeDays: 2, freezerDays: 240, perishable: true, keywords: ["cod"] },
  { name: "tilapia", category: "seafood", fridgeDays: 2, freezerDays: 240, perishable: true, keywords: ["tilapia"] },
  { name: "halibut", category: "seafood", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["halibut"] },
  { name: "crab", category: "seafood", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["crab", "crab meat"] },
  { name: "lobster", category: "seafood", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["lobster"] },
  { name: "scallops", category: "seafood", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["scallop", "scallops"] },
  { name: "clams", category: "seafood", fridgeDays: 2, freezerDays: 90, perishable: true, keywords: ["clam", "clams"] },
  { name: "mussels", category: "seafood", fridgeDays: 2, freezerDays: 90, perishable: true, keywords: ["mussel", "mussels"] },
  { name: "oysters", category: "seafood", fridgeDays: 2, freezerDays: 90, perishable: true, keywords: ["oyster", "oysters"] },
  { name: "sushi", category: "seafood", fridgeDays: 1, freezerDays: null, perishable: true, keywords: ["sushi", "sashimi"] },
  
  // Poultry
  { name: "chicken breast", category: "poultry", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["chicken breast", "chicken breasts"] },
  { name: "chicken thigh", category: "poultry", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["chicken thigh", "chicken thighs"] },
  { name: "whole chicken", category: "poultry", fridgeDays: 2, freezerDays: 365, perishable: true, keywords: ["whole chicken", "roasting chicken"] },
  { name: "ground chicken", category: "poultry", fridgeDays: 2, freezerDays: 120, perishable: true, keywords: ["ground chicken", "chicken mince"] },
  { name: "turkey", category: "poultry", fridgeDays: 2, freezerDays: 270, perishable: true, keywords: ["turkey", "turkey breast"] },
  { name: "ground turkey", category: "poultry", fridgeDays: 2, freezerDays: 120, perishable: true, keywords: ["ground turkey", "turkey mince"] },
  { name: "duck", category: "poultry", fridgeDays: 2, freezerDays: 180, perishable: true, keywords: ["duck"] },

  // Pantry
  { name: "all-purpose flour", category: "pantry", fridgeDays: null, freezerDays: 730, perishable: false, keywords: ["flour", "all purpose flour", "plain flour"] },
  { name: "whole wheat flour", category: "pantry", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["whole wheat flour"] },
  { name: "granulated sugar", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["sugar", "white sugar", "granulated sugar"] },
  { name: "brown sugar", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["brown sugar"] },
  { name: "powdered sugar", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["powdered sugar", "confectioners sugar", "icing sugar"] },
  { name: "baking soda", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["baking soda", "bicarbonate of soda"] },
  { name: "baking powder", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["baking powder"] },
  { name: "salt", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["salt", "table salt", "sea salt"] },
  { name: "pasta", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["pasta", "spaghetti", "penne", "macaroni"] },
  { name: "white rice", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["white rice", "rice"] },
  { name: "brown rice", category: "pantry", fridgeDays: 180, freezerDays: 180, perishable: false, keywords: ["brown rice"] },
  { name: "canned tomatoes", category: "pantry", fridgeDays: 5, freezerDays: 60, perishable: false, keywords: ["canned tomatoes", "tinned tomatoes"] },
  { name: "canned beans", category: "pantry", fridgeDays: 4, freezerDays: 60, perishable: false, keywords: ["canned beans", "tinned beans", "kidney beans", "black beans", "chickpeas"] },
  { name: "canned corn", category: "pantry", fridgeDays: 4, freezerDays: 60, perishable: false, keywords: ["canned corn", "tinned corn"] },
  { name: "canned tuna", category: "pantry", fridgeDays: 4, freezerDays: 60, perishable: false, keywords: ["canned tuna", "tinned tuna"] },
  { name: "peanut butter", category: "pantry", fridgeDays: 90, freezerDays: null, perishable: false, keywords: ["peanut butter"] },
  { name: "jam", category: "pantry", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["jam", "jelly", "preserves"] },
  { name: "honey", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["honey"] },
  { name: "maple syrup", category: "pantry", fridgeDays: 365, freezerDays: null, perishable: false, keywords: ["maple syrup"] },
  { name: "oats", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["oats", "oatmeal", "rolled oats"] },
  { name: "cereal", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cereal", "breakfast cereal"] },
  { name: "bread crumbs", category: "pantry", fridgeDays: 180, freezerDays: 180, perishable: false, keywords: ["breadcrumbs", "bread crumbs"] },
  { name: "crackers", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["crackers", "saltines", "ritz"] },
  { name: "popcorn kernels", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["popcorn kernels", "popcorn"] },
  { name: "coffee beans", category: "pantry", fridgeDays: null, freezerDays: 180, perishable: false, keywords: ["coffee beans", "coffee"] },
  { name: "ground coffee", category: "pantry", fridgeDays: null, freezerDays: 180, perishable: false, keywords: ["ground coffee"] },
  { name: "tea bags", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["tea bags", "tea"] },
  { name: "cocoa powder", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cocoa powder", "cacao powder"] },
  { name: "chocolate chips", category: "pantry", fridgeDays: null, freezerDays: 730, perishable: false, keywords: ["chocolate chips"] },
  { name: "vanilla extract", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["vanilla extract"] },
  { name: "lentils", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["lentils", "lentil"] },
  { name: "dried beans", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["dried beans"] },
  { name: "bouillon cubes", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["bouillon cubes", "stock cubes"] },
  { name: "broth", category: "pantry", fridgeDays: 5, freezerDays: 180, perishable: false, keywords: ["broth", "stock", "chicken broth", "beef broth", "vegetable broth"] },
  { name: "coconut milk", category: "pantry", fridgeDays: 7, freezerDays: 90, perishable: false, keywords: ["coconut milk"] },
  { name: "evaporated milk", category: "pantry", fridgeDays: 5, freezerDays: 90, perishable: false, keywords: ["evaporated milk"] },
  { name: "sweetened condensed milk", category: "pantry", fridgeDays: 14, freezerDays: 90, perishable: false, keywords: ["condensed milk", "sweetened condensed milk"] },
  { name: "gelatin", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["gelatin", "jello"] },
  { name: "cornstarch", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cornstarch", "corn flour"] },
  { name: "cornmeal", category: "pantry", fridgeDays: 365, freezerDays: 730, perishable: false, keywords: ["cornmeal"] },
  { name: "yeast", category: "pantry", fridgeDays: 120, freezerDays: 180, perishable: false, keywords: ["yeast", "active dry yeast", "instant yeast"] },
  { name: "pickles", category: "pantry", fridgeDays: 90, freezerDays: null, perishable: false, keywords: ["pickles", "gherkins"] },
  { name: "olives", category: "pantry", fridgeDays: 21, freezerDays: null, perishable: false, keywords: ["olives", "kalamata", "green olives"] },
  { name: "capers", category: "pantry", fridgeDays: 365, freezerDays: null, perishable: false, keywords: ["capers"] },
  { name: "sundried tomatoes", category: "pantry", fridgeDays: 21, freezerDays: 180, perishable: false, keywords: ["sundried tomatoes", "sun-dried tomatoes"] },
  { name: "canned soup", category: "pantry", fridgeDays: 4, freezerDays: 60, perishable: false, keywords: ["canned soup", "soup"] },
  { name: "instant noodles", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["instant noodles", "ramen"] },
  { name: "seaweed", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["seaweed", "nori", "kombu", "wakame"] },
  { name: "protein powder", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["protein powder"] },
  { name: "apple sauce", category: "pantry", fridgeDays: 10, freezerDays: 60, perishable: false, keywords: ["apple sauce", "applesauce"] },
  { name: "marshmallows", category: "pantry", fridgeDays: null, freezerDays: 120, perishable: false, keywords: ["marshmallows"] },
  { name: "agave nectar", category: "pantry", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["agave nectar", "agave syrup"] },
  
  // Frozen
  { name: "frozen vegetables", category: "frozen", fridgeDays: null, freezerDays: 365, perishable: false, keywords: ["frozen vegetables", "frozen peas", "frozen corn"] },
  { name: "frozen fruit", category: "frozen", fridgeDays: null, freezerDays: 300, perishable: false, keywords: ["frozen fruit", "frozen berries"] },
  { name: "ice cream", category: "frozen", fridgeDays: null, freezerDays: 90, perishable: true, keywords: ["ice cream", "gelato", "sorbet"] },
  { name: "frozen pizza", category: "frozen", fridgeDays: null, freezerDays: 365, perishable: false, keywords: ["frozen pizza"] },
  { name: "frozen dinner", category: "frozen", fridgeDays: null, freezerDays: 365, perishable: false, keywords: ["frozen dinner", "tv dinner", "frozen meal"] },
  { name: "frozen waffles", category: "frozen", fridgeDays: null, freezerDays: 180, perishable: false, keywords: ["frozen waffles", "waffles"] },
  { name: "frozen french fries", category: "frozen", fridgeDays: null, freezerDays: 365, perishable: false, keywords: ["frozen french fries", "frozen fries", "frozen chips"] },
  { name: "frozen fish fillets", category: "frozen", fridgeDays: null, freezerDays: 240, perishable: true, keywords: ["frozen fish", "frozen fish fillets"] },
  { name: "frozen chicken nuggets", category: "frozen", fridgeDays: null, freezerDays: 180, perishable: true, keywords: ["frozen chicken nuggets", "chicken nuggets"] },
  { name: "ice", category: "frozen", fridgeDays: null, freezerDays: null, perishable: true, keywords: ["ice", "ice cubes"] },
  
  // Bakery
  { name: "bread", category: "bakery", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["bread", "sliced bread", "loaf of bread"] },
  { name: "bagels", category: "bakery", fridgeDays: 7, freezerDays: 120, perishable: true, keywords: ["bagel", "bagels"] },
  { name: "croissants", category: "bakery", fridgeDays: 2, freezerDays: 60, perishable: true, keywords: ["croissant", "croissants"] },
  { name: "muffins", category: "bakery", fridgeDays: 3, freezerDays: 90, perishable: true, keywords: ["muffin", "muffins"] },
  { name: "cake", category: "bakery", fridgeDays: 5, freezerDays: 120, perishable: true, keywords: ["cake", "birthday cake"] },
  { name: "cookies", category: "bakery", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["cookie", "cookies", "oreo"] },
  { name: "pie", category: "bakery", fridgeDays: 4, freezerDays: 180, perishable: true, keywords: ["pie", "apple pie", "pumpkin pie"] },
  { name: "donuts", category: "bakery", fridgeDays: 2, freezerDays: 90, perishable: true, keywords: ["donut", "donuts", "doughnut"] },
  { name: "tortillas", category: "bakery", fridgeDays: 21, freezerDays: 180, perishable: true, keywords: ["tortillas", "flour tortillas", "corn tortillas"] },
  { name: "pita bread", category: "bakery", fridgeDays: 7, freezerDays: 90, perishable: true, keywords: ["pita", "pita bread"] },
  { name: "naan", category: "bakery", fridgeDays: 4, freezerDays: 90, perishable: true, keywords: ["naan", "naan bread"] },
  { name: "english muffins", category: "bakery", fridgeDays: 7, freezerDays: 90, perishable: true, keywords: ["english muffin", "english muffins"] },
  
  // Condiments
  { name: "ketchup", category: "condiment", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["ketchup", "tomato ketchup"] },
  { name: "mustard", category: "condiment", fridgeDays: 365, freezerDays: null, perishable: false, keywords: ["mustard", "dijon mustard", "yellow mustard"] },
  { name: "mayonnaise", category: "condiment", fridgeDays: 60, freezerDays: null, perishable: true, keywords: ["mayonnaise", "mayo"] },
  { name: "relish", category: "condiment", fridgeDays: 270, freezerDays: null, perishable: false, keywords: ["relish", "pickle relish"] },
  { name: "bbq sauce", category: "condiment", fridgeDays: 120, freezerDays: null, perishable: false, keywords: ["bbq sauce", "barbecue sauce"] },
  { name: "soy sauce", category: "condiment", fridgeDays: 730, freezerDays: null, perishable: false, keywords: ["soy sauce", "shoyu"] },
  { name: "hot sauce", category: "condiment", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["hot sauce", "sriracha", "tabasco", "cholula"] },
  { name: "salad dressing", category: "condiment", fridgeDays: 90, freezerDays: null, perishable: true, keywords: ["salad dressing", "ranch", "italian dressing", "vinaigrette"] },
  { name: "vinegar", category: "condiment", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["vinegar", "apple cider vinegar", "white vinegar", "balsamic vinegar"] },
  { name: "worcestershire sauce", category: "condiment", fridgeDays: 365, freezerDays: null, perishable: false, keywords: ["worcestershire sauce"] },
  { name: "fish sauce", category: "condiment", fridgeDays: 365, freezerDays: null, perishable: false, keywords: ["fish sauce"] },
  { name: "oyster sauce", category: "condiment", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["oyster sauce"] },
  { name: "hoisin sauce", category: "condiment", fridgeDays: 90, freezerDays: null, perishable: false, keywords: ["hoisin sauce"] },
  { name: "tahini", category: "condiment", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["tahini"] },
  { name: "miso paste", category: "condiment", fridgeDays: 365, freezerDays: null, perishable: true, keywords: ["miso", "miso paste"] },

  // Beverages
  { name: "water", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["water", "bottled water", "mineral water"] },
  { name: "orange juice", category: "beverage", fridgeDays: 10, freezerDays: 240, perishable: true, keywords: ["orange juice", "oj"] },
  { name: "apple juice", category: "beverage", fridgeDays: 10, freezerDays: 240, perishable: true, keywords: ["apple juice"] },
  { name: "soda", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["soda", "pop", "coke", "pepsi", "sprite"] },
  { name: "beer", category: "beverage", fridgeDays: 180, freezerDays: null, perishable: false, keywords: ["beer"] },
  { name: "wine", category: "beverage", fridgeDays: 5, freezerDays: null, perishable: true, keywords: ["wine", "red wine", "white wine"] },
  { name: "vodka", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["vodka", "liquor"] },
  { name: "whiskey", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["whiskey", "whisky", "bourbon", "scotch"] },
  { name: "gin", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["gin"] },
  { name: "rum", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["rum"] },
  { name: "tequila", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["tequila"] },
  { name: "almond milk", category: "beverage", fridgeDays: 10, freezerDays: null, perishable: true, keywords: ["almond milk"] },
  { name: "soy milk", category: "beverage", fridgeDays: 10, freezerDays: null, perishable: true, keywords: ["soy milk", "soymilk"] },
  { name: "oat milk", category: "beverage", fridgeDays: 10, freezerDays: null, perishable: true, keywords: ["oat milk"] },
  { name: "kombucha", category: "beverage", fridgeDays: 30, freezerDays: null, perishable: true, keywords: ["kombucha"] },
  { name: "energy drink", category: "beverage", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["energy drink", "red bull", "monster"] },

  // Snacks
  { name: "potato chips", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["potato chips", "chips", "crisps", "lays"] },
  { name: "tortilla chips", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["tortilla chips", "doritos", "tostitos"] },
  { name: "pretzels", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["pretzels"] },
  { name: "popcorn", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["popcorn", "microwaved popcorn"] },
  { name: "nuts", category: "snack", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["nuts", "mixed nuts"] },
  { name: "trail mix", category: "snack", fridgeDays: null, freezerDays: 180, perishable: false, keywords: ["trail mix"] },
  { name: "granola bars", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["granola bar", "granola bars"] },
  { name: "fruit snacks", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["fruit snacks"] },
  { name: "chocolate bar", category: "snack", fridgeDays: null, freezerDays: 365, perishable: false, keywords: ["chocolate", "chocolate bar", "hersheys", "cadbury"] },
  { name: "candy", category: "snack", fridgeDays: null, freezerDays: 365, perishable: false, keywords: ["candy", "sweets"] },
  { name: "beef jerky", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["beef jerky"] },
  { name: "rice cakes", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["rice cakes"] },
  { name: "seaweed snacks", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["seaweed snacks"] },
  { name: "protein bar", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["protein bar", "protein bars"] },
  { name: "pocky", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["pocky"] },
  { name: "graham crackers", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["graham crackers"] },
  { name: "animal crackers", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["animal crackers"] },
  { name: "goldfish crackers", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["goldfish", "goldfish crackers"] },
  { name: "cheez-its", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cheez-it", "cheez-its"] },
  { name: "fruit leather", category: "snack", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["fruit leather", "fruit roll-up"] },
  
  // Herbs
  { name: "basil", category: "herb", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["basil"] },
  { name: "parsley", category: "herb", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["parsley"] },
  { name: "cilantro", category: "herb", fridgeDays: 10, freezerDays: 180, perishable: true, keywords: ["cilantro", "coriander"] },
  { name: "rosemary", category: "herb", fridgeDays: 21, freezerDays: 180, perishable: true, keywords: ["rosemary"] },
  { name: "thyme", category: "herb", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["thyme"] },
  { name: "oregano", category: "herb", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["oregano"] },
  { name: "mint", category: "herb", fridgeDays: 10, freezerDays: 180, perishable: true, keywords: ["mint"] },
  { name: "dill", category: "herb", fridgeDays: 10, freezerDays: 180, perishable: true, keywords: ["dill"] },
  { name: "sage", category: "herb", fridgeDays: 14, freezerDays: 180, perishable: true, keywords: ["sage"] },
  { name: "chives", category: "herb", fridgeDays: 10, freezerDays: 180, perishable: true, keywords: ["chives"] },
  { name: "lemongrass", category: "herb", fridgeDays: 21, freezerDays: 180, perishable: true, keywords: ["lemongrass"] },
  { name: "marjoram", category: "herb", fridgeDays: 10, freezerDays: 180, perishable: true, keywords: ["marjoram"] },
  { name: "tarragon", category: "herb", fridgeDays: 10, freezerDays: 180, perishable: true, keywords: ["tarragon"] },
  { name: "lavender", category: "herb", fridgeDays: 10, freezerDays: 180, perishable: true, keywords: ["lavender"] },
  { name: "bay leaf", category: "herb", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["bay leaf", "bay leaves"] },

  // Grains
  { name: "quinoa", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["quinoa"] },
  { name: "barley", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["barley"] },
  { name: "couscous", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["couscous"] },
  { name: "farro", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["farro"] },
  { name: "bulgur", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["bulgur", "bulgur wheat"] },
  { name: "millet", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["millet"] },
  { name: "polenta", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["polenta"] },
  { name: "grits", category: "grain", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["grits"] },
  
  // Nuts
  { name: "almonds", category: "nut", fridgeDays: 365, freezerDays: 730, perishable: false, keywords: ["almond", "almonds"] },
  { name: "walnuts", category: "nut", fridgeDays: 365, freezerDays: 730, perishable: false, keywords: ["walnut", "walnuts"] },
  { name: "pecans", category: "nut", fridgeDays: 270, freezerDays: 730, perishable: false, keywords: ["pecan", "pecans"] },
  { name: "cashews", category: "nut", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["cashew", "cashews"] },
  { name: "pistachios", category: "nut", fridgeDays: 270, freezerDays: 365, perishable: false, keywords: ["pistachio", "pistachios"] },
  { name: "peanuts", category: "nut", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["peanut", "peanuts"] },
  { name: "macadamia nuts", category: "nut", fridgeDays: 180, freezerDays: 365, perishable: false, keywords: ["macadamia", "macadamia nuts"] },
  { name: "hazelnuts", category: "nut", fridgeDays: 270, freezerDays: 365, perishable: false, keywords: ["hazelnut", "hazelnuts"] },

  // Oils
  { name: "olive oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["olive oil", "extra virgin olive oil"] },
  { name: "vegetable oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["vegetable oil"] },
  { name: "canola oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["canola oil"] },
  { name: "coconut oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["coconut oil"] },
  { name: "sesame oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["sesame oil"] },
  { name: "avocado oil", category: "oil", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["avocado oil"] },

  // Sauces
  { name: "tomato sauce", category: "sauce", fridgeDays: 7, freezerDays: 180, perishable: false, keywords: ["tomato sauce", "pasta sauce", "passata"] },
  { name: "marinara sauce", category: "sauce", fridgeDays: 7, freezerDays: 180, perishable: false, keywords: ["marinara sauce"] },
  { name: "alfredo sauce", category: "sauce", fridgeDays: 5, freezerDays: null, perishable: true, keywords: ["alfredo", "alfredo sauce"] },
  { name: "pesto", category: "sauce", fridgeDays: 7, freezerDays: 180, perishable: true, keywords: ["pesto", "pesto sauce"] },
  { name: "salsa", category: "sauce", fridgeDays: 14, freezerDays: 60, perishable: true, keywords: ["salsa"] },
  { name: "guacamole", category: "sauce", fridgeDays: 3, freezerDays: 90, perishable: true, keywords: ["guacamole", "guac"] },
  { name: "hummus", category: "sauce", fridgeDays: 7, freezerDays: 120, perishable: true, keywords: ["hummus", "houmous"] },
  { name: "tzatziki", category: "sauce", fridgeDays: 7, freezerDays: null, perishable: true, keywords: ["tzatziki"] },
  { name: "teriyaki sauce", category: "sauce", fridgeDays: 90, freezerDays: null, perishable: false, keywords: ["teriyaki sauce"] },
  { name: "cranberry sauce", category: "sauce", fridgeDays: 14, freezerDays: 60, perishable: false, keywords: ["cranberry sauce"] },
  { name: "apple butter", category: "sauce", fridgeDays: 30, freezerDays: 365, perishable: false, keywords: ["apple butter"] },
  { name: "chutney", category: "sauce", fridgeDays: 30, freezerDays: null, perishable: false, keywords: ["chutney", "mango chutney"] },

  // Spices
  { name: "black pepper", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["black pepper", "peppercorns"] },
  { name: "cinnamon", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cinnamon", "cinnamon sticks"] },
  { name: "cumin", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cumin"] },
  { name: "paprika", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["paprika", "smoked paprika"] },
  { name: "chili powder", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["chili powder"] },
  { name: "garlic powder", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["garlic powder"] },
  { name: "onion powder", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["onion powder"] },
  { name: "turmeric", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["turmeric"] },
  { name: "ginger powder", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["ginger powder", "ground ginger"] },
  { name: "nutmeg", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["nutmeg"] },
  { name: "cloves", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cloves", "ground cloves"] },
  { name: "cayenne pepper", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cayenne pepper"] },
  { name: "red pepper flakes", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["red pepper flakes", "crushed red pepper"] },
  { name: "curry powder", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["curry powder"] },
  { name: "dried oregano", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["dried oregano"] },
  { name: "dried basil", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["dried basil"] },
  { name: "dried thyme", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["dried thyme"] },
  { name: "dried rosemary", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["dried rosemary"] },
  { name: "allspice", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["allspice"] },
  { name: "cardamom", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["cardamom"] },
  { name: "coriander seed", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["coriander seed", "ground coriander"] },
  { name: "mustard seed", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["mustard seed", "mustard powder"] },
  { name: "star anise", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["star anise"] },
  { name: "vanilla bean", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["vanilla bean"] },
  { name: "poppy seeds", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["poppy seeds"] },
  { name: "sesame seeds", category: "spice", fridgeDays: null, freezerDays: null, perishable: false, keywords: ["sesame seeds"] }
];
